### ISSUE TITLE
[MU4 Task] [GP] Tabulature styles preferences to be created in the Style dialog

### ISSUE THREAD

**Issue by boryskuzmenko** [musescore/MuseScore#11664]
**Task description**
This is a preparation task before creating and implementing default styles for Simple and Common TAB staff types. 

- [ ] Design with corresponding element groups to be created in Figma
- [ ] Visualization to be implemented 
- [ ] Checkboxes functionality to be implemented
