### ISSUE TITLE
[MU4 Task] Virtual piano keyboard implementation to be completed 

### ISSUE THREAD

**Issue by abariska** [musescore/MuseScore#12646]
**Task description**
- [ ] Notes should be played when pressing keys on the virtual keyboard
- [ ] Note pitch should be changed for selected note when pressing keys on the virtual keyboard
- [ ] Key color should be blue (not light blue blue) when midi signal is received from external keyboard
- [ ] Keys should repeat external midi keyboard in not-input mode (default)

**Comment by DmitryArefiev** [comment]
Fixed in #13494 (all except 3rd item)

#13505 logged for item №3
