### ISSUE TITLE
[MU4 Task] Update the app icon used inside MuseScore itself

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#12674]
**Task description**
The new purple app icon is not yet used in all places inside the app itself:
- [ ] MuseScore > About MuseScore
- [ ] Home > My account (when logged out)
- [ ] (Installer imagery - that's probably a separate topic)
- [ ] (Anywhere else?)

**Comment by Tantacrul** [comment]
@HemantAntony - remember we discussed this one before. Do you want it?

@jessjwilliamson can provide you with the logos

**Comment by HemantAntony** [comment]
I'll take it :)
