### ISSUE TITLE
[MU4 Issue] Muse Sounds instruments playback range is too small - summary for developers

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#16244]
This is the summary of #13894, which has become an unwieldy discussion, digressing to not directly related topics. 

(Read "must" and "should" as "someone said that … must/should …".)

**Describe the bug**
For the following Muse Sounds instruments, their playable range is considered too small:
- Woodwinds:
    - [ ] Clarinet in Bb stops at G6 (concert pitch)
        - Db3 (convert pitch) is missing, which is the bottom note for A clarinet, for which the Bb clarinet sound is often used as a replacement, because there is no A clarinet; some Bb clarinets have extensions to play notes that low [[source]](https://github.com/musescore/MuseScore/issues/13894#issuecomment-1339104326)
        - At the top, someone wants C7 at least; has even seen G7 [[source]](https://github.com/musescore/MuseScore/issues/13894#issuecomment-1366039401)
    - [ ] Oboe stops at F6 (A6 would be more reasonable) [[source]](https://github.com/musescore/MuseScore/issues/13894#issuecomment-1295784276)
    - [ ] English horn stops at G5 but should go up to B5 [[source]](https://github.com/musescore/MuseScore/issues/13894#issuecomment-1361390446)
    - [ ] Bassoon stops at A4 (D5 would be more reasonable, and repertoire asks for it) [[source]](https://github.com/musescore/MuseScore/issues/13894#issuecomment-1295784276)
        Currently the bassoon can't even play Rite of Spring
        Someone even wants E5 and F5
        Or even Bb5 [[source]](https://github.com/musescore/MuseScore/issues/13894#issuecomment-1387298198)
    - [ ] #15458 
    - [ ] General comment: "I know for wind instruments at least, there is no hard limit to how high you can go, it just gets harder, so realistically, the best solution would just be to pitch the samples up." [[source]](https://github.com/musescore/MuseScore/issues/13894#issuecomment-1293668325)

- Brass:
    - [ ] Trumpet stops at C6 (concert); jazz players regularly play up to F6 and sometimes beyond. [[source]](https://github.com/musescore/MuseScore/issues/13894#issuecomment-1293652240)
        - And doesn't go below F3 [[source]](https://github.com/musescore/MuseScore/issues/13894#issuecomment-1351992786)
        - Someone says 'classical' trumpet must definitely go above D [[source]](https://github.com/musescore/MuseScore/issues/13894#issuecomment-1358911880)

- Voices:
    - [ ] The ranges for each of SATB are considered somewhat small [[source]](https://github.com/musescore/MuseScore/issues/13894#issuecomment-1294843273) 
    - [ ] In many scores, for example Soprano and Alto are notated on one staff and therefore share a mixer channel; Muse Sounds should ideally provide just "Women" and "Men" sounds that cover the whole range by mixing/layering Soprano and Alto or Tenor and Bass, and ideally also a full "Choir" sound that covers everything by mixing all four voices [[source]](https://github.com/musescore/MuseScore/issues/13894#issuecomment-1335941545)
    - [ ] Problems for baritons: some notes too low for tenors, others too high for basses; this would be solved by a "Men" sound [[source]](https://github.com/musescore/MuseScore/issues/13894#issuecomment-1364180797)

- Strings:
    - [ ] Violin 1 (solo) stops at B6
        (also, as reported in [#14080 (comment)](https://github.com/musescore/MuseScore/issues/14080#issuecomment-1292873111), the A6 sounds a bit flat, so <img width="34" alt="Scherm­afbeelding 2022-10-27 om 16 31 24" src="https://user-images.githubusercontent.com/48658420/198315257-5001921f-2277-4b1b-b41c-a26c8968a153.png"> sounds out of tune)

    - [ ] Violin 2 (solo) stops at C7

- Rest:
    - [ ] Harpsichord only goes from ... to B5; G1 to F6 is required in some harpsichord music [[source]](https://github.com/musescore/MuseScore/issues/13894#issuecomment-1357293283)
        - and B6 for Brandenburg 5 [[source]](https://github.com/musescore/MuseScore/issues/13894#issuecomment-1416818300) 

- More special requests (maybe somewhat niche)
    - [ ] 108 key grand piano
    - [ ] Flute: low Bb (and maybe even a few notes below) [[source]](https://github.com/musescore/MuseScore/issues/13894#issuecomment-1416872163)
    - [ ] Low A bassoons [[source]](https://github.com/musescore/MuseScore/issues/13894#issuecomment-1371494564)
    - [ ] Vocal Fry and the Subharmonic range, making people's voices sound an octave+ lower than they truly are [[source]](https://github.com/musescore/MuseScore/issues/13894#issuecomment-1400473062)

Users say unanimously that they would prefer anything like pitch-shifted, borrowed or inferior samples over no samples at all.

--- 

@ Users: if you want to add something, please do so at #13894 and I will add it here
