### ISSUE TITLE
Refinements checklist for the new Parts/Score interaction feature

### ISSUE THREAD

**Issue by mike-spa** [musescore/MuseScore#19527]
### Bug description

@cbjeukendrup @bkunda @oktophonie feel free to dump here all the requests (preferably numbered so I can keep track more easily).

**Comment by cbjeukendrup** [comment]
- [ ] 1. Bug: 
   1. Add ottava
   2. Exclude it from parts
   3. Drag a note in a part => the note does not properly follow the mouse. It always stays an octave higher than the mouse. (the laggy-ness is just my computer; that's not the problem.)


   https://github.com/musescore/MuseScore/assets/48658420/07220fd0-83a5-4eba-bd94-735b3394110d


- [ ] 2. Something questionable:
   1. Select a system header clef
   2. Enable "exclude from parts"
   3. Disable "exclude from parts" => Now there is suddenly a new clef in the parts, that is not a system header clef but a real clef change! But that clef change is not in the main score. 
   4. Enter some notes before and after the system break in question, via the main score
   5. When I then switched to the part score, MuseScore crashed. 

   So the question is: should the "exclude from parts" checkbox be available for system header clefs? And if yes, how should it behave?

- [ ] 3. Crash when creating parts for a score containing no measures nor boxes: see https://github.com/musescore/MuseScore/pull/18722#discussion_r1336484024.

**Comment by sammik** [comment]
Unticking "Exclude from parts" on "Title frame" adds extra (title) frame(s).

https://github.com/musescore/MuseScore/assets/1646034/a5cbb0ef-822e-44d3-a67a-eaca29e7c2da

1. open parts
2. on score, select title frame
3. properties tab tick "Exclude from parts"
4. untick "Exclude..."
5. see - extra frame(s) added

probably distantly relative to #19476

**Comment by sammik** [comment]
- [ ] 5. Unlinked elements shouldn't have "Synchronisation dialog" in properties.

![Unlinked-dialog](https://github.com/musescore/MuseScore/assets/1646034/4584d78f-819c-4180-8686-f86045f5468e)

**Comment by mike-spa** [comment]
- [ ] 6. 
- Go to a part, click on the title text, deselect the Text linking property.
- Change the title text to something else, it won't affect the score (good).
- Change the title in the score -> it will also affect the part (but it shouldn't cause it was desync-ed).

**Comment by mike-spa** [comment]
- [ ] 7.
- Enter rehearsal mark. 
- Go to the part, unlink position and appearance, modify them as preferred (for instance, make the font bigger in the part). Changed will not affect the score (good).
- Go to the part, modify the text itself of the rehearsal mark -> it will also change the size of the mark in the score (it shouldn't).

**Comment by mike-spa** [comment]
- [ ] 8. 
- Enter two notes. Enter dynamics on the first note.
- In the score, drag the dynamic until it snaps to the next note -> The change in anchor note isn't reflected in the part, meaning the dynamic in the part (despite having all properties still linked) is still attached to the first note

**Comment by oktophonie** [comment]
- [] 9. Add layout items (system/page breaks, keep-together item) to the include/exclude system

**Comment by bkunda** [comment]
- [ ] 11. Main score position property changes for slurs and ties don't synchronise with the part unless the part is already open [See video](https://www.dropbox.com/scl/fi/4vwva5vwkzzw10lydtx60/slurs-ties-position-property-not-autosyncing.mov?rlkey=qwr961o8o7g04dx11hf8dzhh3&dl=0)

**Comment by bkunda** [comment]
- [ ] 12. Auto-place property not synchronising between main score and parts [See video](https://www.dropbox.com/s/h2hfdwxaaq6r0ke/auto-place-not-syncing.mov?dl=0)

**Comment by sammik** [comment]
- [ ] 13. horizontal frame and section break issues

This one is a bit more complicated
Section break is at the moment "always included in parts". But once **[9.](https://github.com/musescore/MuseScore/issues/19527#issuecomment-1781060013_)** will be implemented, all layout elements will have this problem.

a) If section break is added to horizontal frame it is missing in part. It is because frame itself is not in part. But is this intended? I think, it would be better, in souch situations add section break (layout item) to preseding measure in part.

b) If frame is included into parts, section break is still missing in parts.

c) If section break is added to frame, which is included in parts, it is added to next measure in parts.
(Or if section break is added into part, it is in next measure in score and other parts)

**Comment by sammik** [comment]
- [ ] 14. #19909

**Comment by avvvvve** [comment]
- [ ] #19981

This is definitely a nice-to-have and not essential for launch.

**Comment by avvvvve** [comment]
- [ ] 16. #19982

**Comment by avvvvve** [comment]
- [ ] 16.
Tuplet numbers do not change color when unsynced in parts.
1. Open a part that has tuplets
2. Click a tuplet number in the score
3. Reposition it (or simply turn off the "Position" toggle)
4. See that it does not turn orange.

![scorenpart-tuplet-color](https://github.com/musescore/MuseScore/assets/20806406/83a53040-1786-4ab1-ad7e-7ed7f1b3b513)

Note that tuplet brackets are already changing color correctly:
![scorenpart-tuplet-brackets](https://github.com/musescore/MuseScore/assets/20806406/0fbc072e-cc30-4c2c-b767-130eafca4bd7)

**Comment by avvvvve** [comment]
- [ ] 17.

System elements (like tempo markings) sometimes shift when the "Position" toggle is turned off and then back on. It can be reset back to its original position by turning the "Text" toggle off and on again. It doesn't happen in every part, but seems to happen more when there is an element on the neighboring system above it that is close to it.

https://github.com/musescore/MuseScore/assets/20806406/319f4dd3-888e-4650-9017-15a75d98e629

**Comment by miiizen** [comment]
Adding to [16](https://github.com/musescore/MuseScore/issues/19527#issuecomment-1804312149) - this is also the case for the text on textlines
<img width="564" alt="Screenshot 2023-11-10 at 16 20 36" src="https://github.com/musescore/MuseScore/assets/26510874/6d145293-18ac-4e28-8ce9-42dbc2eef0ec">

**Comment by avvvvve** [comment]
- [ ] 18. In parts, the following elements should _not_ be able to be de-synced from the score—so, do not show "Score and part synchronization" in their Properties:

- Notes
- Rests
- Key signatures
- Time signatures
- Barlines

From Bradley's design:
![image](https://github.com/musescore/MuseScore/assets/20806406/96f046c8-1449-41d3-a6e1-67804adf6468)
