### ISSUE TITLE
To-do list for MuseScore.org Download page

### ISSUE THREAD

**Issue by shoogle** [musescore/MuseScore#20658]
- [x] Link to portable Windows build
- [x] Link to ARM AppImages for Linux
- [ ] Link to older versions on GitHub releases
- [ ] Move Linux & BSD community packages to the Handbook
    - This will enable the community to add detailed notes about each package (e.g. to say if it is outdated, has bugs, or requires additional steps to get working).
- [ ] Link to community packages Handbook page

**Comment by cbjeukendrup** [comment]
I think it would also be good to link to the Downloads page from the home page. I'd replace "Download an older version" with "More download options".

**Comment by bkunda** [comment]
Closing as this has now been added to a separate task tracker for the website.
