### ISSUE TITLE
Add 'Voice assignment' property to sound flags and playing technique annotations

### ISSUE THREAD

**Issue by avvvvve** [musescore/MuseScore#23368]
_Follow-up to #19137_

### Task description

Sound flags and playing technique annotations should have the same 'Voice assignment' property as dynamics and hairpins. This setting does not need to affect positioning of these elements as it does for dynamics and hairpins.

### Tasks

- [ ] Show the same properties whether the text or sound flag button portion of a sound flag is selected; add 'Voice assignment' property
- [ ] Playing technique annotation properties: add 'Voice assignment' property
- [ ] Remove 'Apply selection to all staves' from the context menu in the sound flags popup (replaced by the 'All' options in 'Voice assignment')
- [ ] In Preferences > Note input, change wording of 'Dynamics & hairpins' section to account for sound flags and playing technique annotations
     <img width="327" alt="image" src="https://github.com/musescore/MuseScore/assets/20806406/7da71f04-1db8-42bc-b43e-b7ee4427ad37">

### Design

Ping @avvvvve for Figma link :)

_Note: Waiting for sign-off to change the wording of 'Apply to voice' to 'Voice assignment'_
