### ISSUE TITLE
Add keyboard shortcuts to control 'Voice assignment' property

### ISSUE THREAD

**Issue by avvvvve** [musescore/MuseScore#23370]
We currently have the following shortcut actions that can be used to move certain elements, like notes, from one voice to another when selected:
<img width="882" alt="image" src="https://github.com/musescore/MuseScore/assets/20806406/bd2982a5-6c41-450d-b95e-bcbb2c3227ef">

Now that dynamics and hairpins can be assigned to individual voices, these shortcuts should also work with those elements. Additionally, we can add actions to set the voice to either 'All voices on instrument' or 'All voices on this staff only'.

### Tasks

- [ ] Make each of the 'Use voice [#] shortcuts' usable on dynamics on hairpins to control their 'Voice assignment' property
- [ ] Add two new shortcut actions with the following default shortcuts:
     - [ ] 'Use all voices on instrument'
          - Mac: <kbd>Cmd</kbd> + <kbd>Option</kbd> + <kbd>0</kbd>
          - Windows: <kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>0</kbd>
     - [ ] 'Use all voices on this staff only'
          - Mac: <kbd>Cmd</kbd> + <kbd>Option</kbd> + <kbd>-</kbd>
          - Windows: <kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>-</kbd>
     - These shortcuts will be used to choose from the two nested 'All' options for the 'Voice assignment' property on multi-staff instruments. If the element is on a single-staff instrument, using either of these shortcuts should set 'Voice assignment' to 'All'.

_Note: Waiting for sign-off to change the wording of 'Apply to voice' to 'Voice assignment'_

**Comment by avvvvve** [comment]
@shoogle As far as I can tell these shortcuts not already taken by other actions, but just wanted to check with you that they make sense.

@bkunda Tagging for triage.

I know the wording of 'Use all voices...' is a bit awkward since it's really 'Assign to all voices...', but it's the only way for these to show up in the shortcuts list alphabetically next to the other voice assignment shortcuts. Alternatively, we could change the existing shortcuts to the form 'Assign to voice [#]'.

**Comment by avvvvve** [comment]
Good point, and those would likely be used much more than these shortcuts.

Another couple options, based on their inclusion in number pads and their position next to each other on QWERTY keyboards:

- Cmd+Opt+/ and Cmd+Opt+.

OR

- Cmd+Opt+= and Cmd+Opt+-

**Comment by shoogle** [comment]
How about <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>0</kbd> for "Use all voices on instrument"?

We could use <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>Shift</kbd>+<kbd>0</kbd> or <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>-</kbd> for "Use all voices on stave".

The advantage of <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>-</kbd> is it makes <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>=</kbd> the obvious choice for "Use all voices on system" if we add that again in the future.

**Comment by avvvvve** [comment]
I'd assume if we added the system option, we'd order them as such in the 'All' menu:

- All voices on system
- All voices on instrument (selected by default)
- All voices on this staff only

So then I'd keep the order of the shortcuts as such, as they're laid out left to right on the keyboard:

- System:
     <kbd>Cmd</kbd>+<kbd>Opt</kbd>+<kbd>0</kbd>
- Instrument:
     <kbd>Cmd</kbd>+<kbd>Opt</kbd>+<kbd>-</kbd>
- Staff:
      <kbd>Cmd</kbd>+<kbd>Opt</kbd>+<kbd>=</kbd>

**Comment by shoogle** [comment]
The way I see it:

- <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>0</kbd> (zero) applies to the instrument
- <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>-</kbd> (minus) applies to something _smaller_ than the instrument
- <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>+</kbd> (plus) applies to something _larger_ than the instrument (<kbd>+</kbd> is the same key as <kbd>=</kbd> on QWERTY keyboards).

Also, <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>0</kbd> is the intuitive shortcut that users might try based purely on the "Use voice" shortcuts. We should use it for the default option that we want most people to use most of the time. We could debate whether _instrument_ or _staff_ should be the default, but nobody would argue that _system_ should be the default.

**Comment by avvvvve** [comment]
I'm sold! I'll update the description with <kbd>0</kbd> and <kbd>-</kbd> as the shortcuts.
