### ISSUE TITLE
MuseScore 3.5 Beta. PRs to be merged

### ISSUE THREAD

**Issue by anatoly-os** [musescore/MuseScore#6027]
- [x] #5564: Page width shortcut
- [x] #5637: Same Beat/Measure options in select all similar dialogue
- [x] #5568: Update range transposition shortcut to selection only
- [x] #5620: Some Extra Navigation Shortcuts
- [x] #5577: Diatonic transpose shortcuts which keep degree alterations.
- [x] #5623: Extra default zoom preferences 
- [x] #5922
- [ ] #4757
- [ ] #5508
- [ ] #5779
- [ ] #5965
- [x] #6003

**Comment by njvdberg** [comment]
- [ ] #6023
- [ ] #6024 
- [ ] #5965 
- [ ] #5437 / #5560 Both are not the ideal solution but I'm not sure it's worth waiting for that better solution and leave the issue until then.

**Comment by Howard-C** [comment]
How about #5773 and #5602

**Comment by njvdberg** [comment]
- [ ] #6035 shouldn't be a real risk

**Comment by Jojo-Schmitz** [comment]
* [ ] #4824 Implements portamento for fluid
* [ ] #5381 Add Petaluma font 
* [ ] #5934 Update Bravura to 1.36

**Comment by tobik** [comment]
#4220 Breath marks for voices
#5896 Merge matching rests for voices
#5897 Collision avoidance for rests

**Comment by Howard-C** [comment]
#6045

**Comment by njvdberg** [comment]
- [ ] #6049 (replaces #6024 which was on the wrong branch)

**Comment by AntonioBL** [comment]
[ ] https://github.com/musescore/MuseScore/pull/5774
[ ] https://github.com/musescore/MuseScore/pull/5794 -> It should solve a serious bug, but the PR needs review and some testing under Windows and Linux
[ ] https://github.com/musescore/MuseScore/pull/5969 -> It should solve a serious regression (very very long load time) with respect to 3.4.2; it works in its current state, but it is not elegant (a lot of code duplication): I need help in finalizing it

**Comment by Jojo-Schmitz** [comment]
> * [ ]  #6035 shouldn't be a real risk

This is actually not merged into 3.x yet, only into master

**Comment by AntonioBL** [comment]
- [ ] #6084 - [User fonts not visible to MuseScore 3 (Windows 10)](https://musescore.org/en/node/280244)

**Comment by MarcSabatella** [comment]
#6081 fixes a pretty serious lyric layout issue that has been with us since 3.0

**Comment by dmitrio95** [comment]
Here is the list of my pull requests which could potentially be merged. Some of them have been listed here but I'll include them to my list anyway for completeness.

## Bugfixes
- [ ] #6089

## Plugin API proposals
These pull requests should be safe to be merged for 3.5 but can wait for later versions and more detailed review as well.
- [ ] #5961 - simply a documentation change
- [ ] #6065 - style settings API
- [ ] #6085 - tuplets support + support for adding rests and tuplets with Cursor
- [ ] #6090 - instruments and channels
- [ ] #6091 - selecting elements from plugins

**Comment by lvinken** [comment]
https://github.com/musescore/MuseScore/pull/6086 - MusicXML fixes (to better support export to braille) has been replaced by https://github.com/musescore/MuseScore/pull/6088

**Comment by MarcSabatella** [comment]
- [ ] #6104 - fixes bug in new chord symbol playback feature

**Comment by Marr11317** [comment]
[ ] #6105 fixes a little layout bug introduced with #5811

**Comment by MarcSabatella** [comment]
- [ ] #6107 - fixes a bug where a common chord symbol doesn't play back

**Comment by Howard-C** [comment]
#6122 - fixes two problems with ambiti

**Comment by MarcSabatella** [comment]
- [ ] #6100 - a potentially significant layout improvement for certain cases

**Comment by Spire42** [comment]
- #6106 - [Disable save prompt for empty scores](https://musescore.org/en/node/305724)

This is a small tweak to #5784 that suppresses the save prompt in cases where it isn't needed and is just annoying.

**Comment by MarcSabatella** [comment]
Four usability improvements with regard to selection, they each take something that does nothing reasonable at all now and makes them do what the user expects:

- [ ] #6137 - click / shift+click to similar similar elements in range
- [ ] #6138 - shift+click empty space no longer loses selection
- [ ] #6139 - ctrl+click on range converts to list
- [ ] #6140 - "R" repeats single note in normal mode

**Comment by njvdberg** [comment]
- [ ] #6060 - Fix #281759 - Chord Symbols: allow option to ensure uniform vertical alignment
- [ ] #6110 - Fix #305656 Two piano instruments shown for a single piano part after save/load
- [ ] #6116 - Fix #305750 - Nested tuplets in linked staves lead to corruption
- [ ] #6124 - Fix 257581 - Changes to Measure properties are not propagated between score and existing linked parts after save/reload
- [ ] #6129 - Fix #270043 - Corruption on deleting initial rest in voice 2 tuplet
- [ ] #6144 - Fix #97376 - Split Measure breaks slurs and ties

**Comment by blackears** [comment]
#6099 - Now keeping length, ontime and velocity data when copying notes.
#6112 - Add ability to change note to tuplet to right click menu in Piano Roll Editor
#6113 - Make dragging note in PRE visible for tools other than Select

**Comment by Spire42** [comment]
- [ ] #6168 - [Status bar should display playback pitch of selected note](https://musescore.org/en/node/306370)

Requested by a user [here](https://musescore.org/en/node/306320). Makes working with transposing instruments a little easier and less confusing.

**Comment by tobik** [comment]
May I ask again for #4220 Breath marks for voices (already mentioned above)? This is a simple change, reviewed and waiting for a long time. It is requested by different people: [85876](https://musescore.org/en/node/85876), [110431](https://musescore.org/en/node/110431), [268837](https://musescore.org/en/node/268837), [283591](https://musescore.org/en/node/283591) and finally would allow me to use a official MuseScore release again.

Thanks for considering.

**Comment by shoogle** [comment]
- [ ] #6173 if it's not too late. This is a major improvement to accessibility requested by RNIB.

**Comment by njvdberg** [comment]
If it is still possible:
- [ ] [#6180 - Various type of edits change the measure count](https://github.com/musescore/MuseScore/pull/6180)
- [ ] [#6183 - Crash undoing add instruments](https://github.com/musescore/MuseScore/pull/6183)

**Comment by Spire42** [comment]
- [ ] #6185 - [Toolbar item states are incorrect after applying preferences](https://musescore.org/en/node/306502)

**Comment by Spire42** [comment]
- [ ] #6186 - [Improvements to zoom functionality](https://musescore.org/en/node/306509)

**Comment by Spire42** [comment]
- [ ] #6187 - [Improvements to the splash screen](https://musescore.org/en/node/306512)

**Comment by Spire42** [comment]
- [ ] #6190 - [Control playback speed with the keyboard](https://musescore.org/en/node/306524)

Requested by a user [here](https://musescore.org/en/node/305840).

**Comment by Spire42** [comment]
- [ ] #6194 - minor code cleanup

Minor cleanup of #6186 of #6187, courtesy of @Jojo-Schmitz.

**Comment by Jojo-Schmitz** [comment]
Any chance for any of the PRs that didn't make it into the Beta to make it into RC?

 #4757
 #5508
 #5779
 #5965
 #5437 / #5560 
 #5731
 #5602
 commented on 4 May • 
 #4824 or its rebased #5853 Implements portamento for fluid
 #5381 Add Petaluma font
 #5934 Update Bravura to 1.37
 #5958 Fix multiple issues with chord diagrams in MusicXML export
 #6002 Add support for triple sharp and triple flat
 #6124 - Fix 257581 - Changes to Measure properties are not propagated between score and existing linked parts after save/reload
 #6099 - Now keeping length, ontime and velocity data when copying notes.
 #6112 - Add ability to change note to tuplet to right click menu in Piano Roll Editor
 #6113 - Make dragging note in PRE visible for tools other than Select
 #6153 - Adding notes to a tuplet now adds them with respect to tuplet space
