### ISSUE TITLE
[MuseScore 3.5 Alpha] The list of known regressions

### ISSUE THREAD

**Issue by anatoly-os** [musescore/MuseScore#6055]
This issue contains all the known issues found in MuseScore 3.5 Alpha release:

* [x] [#305704: Can't export mp3 on OS X 10.15 using MuseScore 3.5.0](https://musescore.org/en/node/305704) (forum topic)
* [x] [#306317: Multi-page scores yield invalid MusicXML](https://musescore.org/en/node/306317)

**Comment by Jojo-Schmitz** [comment]
[Crash on leaving preferences dialog if no score is loaded](https://musescore.org/en/node/305048)

**Comment by Howard-C** [comment]
- [#305007: Stems too long for chords with single-note tremolo](https://musescore.org/node/305007)

**Comment by njvdberg** [comment]
- [ ] [#305135: Chord symbols won't go back to original position after reverting changes](https://musescore.org/en/node/305135)

**Comment by AntonioBL** [comment]
- [ ] https://github.com/musescore/MuseScore/pull/5969 - [fix #303983 : MuseScore takes very long on opening some 2.x scores](https://musescore.org/en/node/303983)

**Comment by Jojo-Schmitz** [comment]
> * [ ]  #5969 - [fix #303983 : MuseScore takes very long on opening some 2.x scores](https://musescore.org/en/node/303983)

Well, not really a 3.5 Alpha regression, is it? But certainly a PR we should have in 3.5 Beta

**Comment by jeetee** [comment]
* [ ]  #6084 - [fix #280244: \[Workaround\] User fonts not visible to MuseScore 3 (Windows 10)](https://musescore.org/en/node/280244)

**Comment by Jojo-Schmitz** [comment]
> * [ ]   #6084 - [fix #280244: [Workaround] User fonts not visible to MuseScore 3 (Windows 10)](https://musescore.org/en/node/280244)

Certainly a nice to have PR for 3.5, but also certainly not a known regression of 3.5 Alpha

**Comment by calculuswhiz** [comment]
https://musescore.org/en/node/301138

**Comment by Jojo-Schmitz** [comment]
> Is this the right place? Sorry if it's not...
> https://musescore.org/en/node/301138

That is not a 3.5 Alpha regression

**Comment by anatoly-os** [comment]
@Jojo-Schmitz let's remove https://musescore.org/en/node/305199 and https://musescore.org/en/node/305743 from your list. First one is more a feature request, second one was decided to address in MU 4 with the new inspector.

**Comment by Jojo-Schmitz** [comment]
Fine by me

**Comment by Jojo-Schmitz** [comment]
added a new regression to my list, Leon regards this a show-stopper

**Comment by MarcSabatella** [comment]
Me too, it renders MusicXML export all but useless.

**Comment by MarcSabatella** [comment]
- [ ] https://musescore.org/en/node/304959

**Comment by anatoly-os** [comment]
Thanks to everyone! We've finally beaten all known regressions!

**Comment by MarcSabatella** [comment]
Impressive, thanks everyone!
