### ISSUE TITLE
[MU4 Issue] PRs from 3.x  to be merged into / ported to master

### ISSUE THREAD

**Issue by Jojo-Schmitz** [musescore/MuseScore#6079]
* [x] #6028
* [x] #6043
* [x] #6046
* [x] #6048
* [x] #6050
* [x] #6051 (may not be wanted due to the pending major design changes)
* [x] #6052
* [x] #6061
* [x] #6063
* [x] #6064
* [x] #6065
* [x] #6066
* [x] #6072
* [x] #6073
* [x] #6076
* [x] #6077
* [x] #6078
* [x] #6082
* [x] #6083
* [x] #6087
* [x] #6088
* [x] #6089
* [x] #6092
* [x] #6093
* [x] #6094
* [x] #6101
* [x] #6103
* [x] #6104
* [x] #6111

**Comment by Marr11317** [comment]
I am not sure I get it. If all PRs solve a bug or add functionality, shouldn't they all get merged into master?
In other words, what PRs should be excluded from this list?

**Comment by Jojo-Schmitz** [comment]
Probably none, but these specifically habe been merged to 3.x but not yet into master, this issue here is nothing but a reminder

**Comment by Jojo-Schmitz** [comment]
@anatoly-os is using his own book-keeping, so this issue isn't needed

**Comment by shoogle** [comment]
List of PRs that have been merged into the 3.x branch:
https://github.com/musescore/MuseScore/pulls?q=is%3Apr+is%3Amerged+base%3A3.x

**Comment by Jojo-Schmitz** [comment]
161... (minus the ~30 listed above) and counting

**Comment by Jojo-Schmitz** [comment]
* [ ] ~#6249~ #6325

**Comment by shoogle** [comment]
We can make the list more manageable by each taking care of our own PRs. [My PRs](https://github.com/musescore/MuseScore/pulls?q=is%3Apr+is%3Amerged+base%3A3.x+author%3Ashoogle) are:

- [ ] #6173
- [ ] #6210
- [ ] #6245
- [ ] #6249, ported by #6325

*I will edit this comment to add any future PRs on 3.x, and to add "ported by #xxxx" when I create the corresponding PR on master. I will tick the checkbox when the PR is merged into master, or when we decide it is not needed (in which case I will add a comment to explain why).*

That leaves these PRs that are [not mine](https://github.com/musescore/MuseScore/pulls?q=is%3Apr+is%3Amerged+base%3A3.x+-author%3Ashoogle) (and these are [not mine or Jojo's](https://github.com/musescore/MuseScore/pulls?q=is%3Apr+is%3Amerged+base%3A3.x+-author%3Ashoogle+-author%3AJojo-Schmitz)). Anybody can view their own PRs [here](https://github.com/musescore/MuseScore/pulls?q=is%3Apr+is%3Amerged+base%3A3.x+author%3A%40me).

**Comment by SKefalidis** [comment]
[ ] #6191 
[ ] #6196

**Comment by Jojo-Schmitz** [comment]
@SKefalidis what about your #6198? Seems embedded into #6196 , right?

**Comment by SKefalidis** [comment]
> @SKefalidis what about your #6198? Seems embedded into #6196, right?

Yes

**Comment by Jojo-Schmitz** [comment]
We'd need to check the PRs from 

* @MarcSabatella: https://github.com/musescore/MuseScore/pulls?q=is%3Apr+is%3Amerged+base%3A3.x+author%3AMarcSabatella
* @mattmcclinch: https://github.com/musescore/MuseScore/pulls?q=is%3Apr+is%3Amerged+base%3A3.x+author%3Amattmcclinch
* @igorkorsukov: https://github.com/musescore/MuseScore/pulls?q=is%3Apr+is%3Amerged+base%3A3.x+author%3Aigorkorsukov
* @rettinghaus: https://github.com/musescore/MuseScore/pulls?q=is%3Apr+is%3Amerged+base%3A3.x+author%3Arettinghaus
* @worldwideweary: https://github.com/musescore/MuseScore/pulls?q=is%3Apr+is%3Amerged+base%3A3.x+author%3Aworldwideweary
* @Spire42: https://github.com/musescore/MuseScore/pulls?q=is%3Apr+is%3Amerged+base%3A3.x+author%3ASpire42
* @AntonioBL: https://github.com/musescore/MuseScore/pulls?q=is%3Apr+is%3Amerged+base%3A3.x+author%3AAntonioBL
* @tobik: https://github.com/musescore/MuseScore/pulls?q=is%3Apr+is%3Amerged+base%3A3.x+author%3Atobik
* @Howard-C: https://github.com/musescore/MuseScore/pulls?q=is%3Apr+is%3Amerged+base%3A3.x+author%3AHoward-C
* @njvdberg: https://github.com/musescore/MuseScore/pulls?q=is%3Apr+is%3Amerged+base%3A3.x+author%3Anjvdberg
* @Marr11317: https://github.com/musescore/MuseScore/pulls?q=is%3Apr+is%3Amerged+base%3A3.x+author%3AMarr11317
* @dmitrio95: https://github.com/musescore/MuseScore/pulls?q=is%3Apr+is%3Amerged+base%3A3.x+author%3Admitrio95
* @blackears: https://github.com/musescore/MuseScore/pulls?q=is%3Apr+is%3Amerged+base%3A3.x+author%3Ablackears
* @IsaacWeiss: https://github.com/musescore/MuseScore/pulls?q=is%3Apr+is%3Amerged+base%3A3.x+author%3AIsaacWeiss
* @jthistle: https://github.com/musescore/MuseScore/pulls?q=is%3Apr+is%3Amerged+base%3A3.x+author%3Ajthistle

**Comment by lvinken** [comment]
Like some other developers, I also maintain a private list of PRs to be synced to master. As I typically only work on MusicXML import/export, all my PRs apply equally well to master as to the current release.

As was mentioned before, having a public agreement on how we maintain such list could make the process more  uniform and transparent.

**Comment by shoogle** [comment]
@lvinken, let's not overthink this. I [suggested a system](https://github.com/musescore/MuseScore/issues/6079#issuecomment-656654608) that seems as good as any, but really it's enough to know that you plan to take care of your own PRs.

**Comment by njvdberg** [comment]
- [x] [#6048](https://github.com/musescore/MuseScore/pull/6048)
 - [ ] [#6049](https://github.com/musescore/MuseScore/pull/6049) Merges cleanly into master.
 - [x] [#6060](https://github.com/musescore/MuseScore/pull/6060) Replaced by [#6219](https://github.com/musescore/MuseScore/pull/6219)
 - [x] [#6067](https://github.com/musescore/MuseScore/pull/6067)
 - [x] [#6087](https://github.com/musescore/MuseScore/pull/6087)
 - [x] [#6093](https://github.com/musescore/MuseScore/pull/6093)
 - [ ] [#6110](https://github.com/musescore/MuseScore/pull/6110) Merges cleanly into master.
 - [ ] [#6116](https://github.com/musescore/MuseScore/pull/6116) Merges cleanly into master.
 - [ ] [#6125](https://github.com/musescore/MuseScore/pull/6125) Merges cleanly into master.
 - [ ] [#6129](https://github.com/musescore/MuseScore/pull/6129) Merges cleanly into master.
 - [ ] [#6132](https://github.com/musescore/MuseScore/pull/6132) Merges cleanly into master.
 - [ ] [#6144](https://github.com/musescore/MuseScore/pull/6144) Merges cleanly into master.
 - [ ] [#6164](https://github.com/musescore/MuseScore/pull/6164) Merges cleanly into master.
 - [ ] [#6180](https://github.com/musescore/MuseScore/pull/6180) Merges cleanly into master.
 - [ ] [#6183](https://github.com/musescore/MuseScore/pull/6183) Merges cleanly into master.
 - [ ] [#6216](https://github.com/musescore/MuseScore/pull/6216) Merges cleanly into master.
 - [ ] [#6219](https://github.com/musescore/MuseScore/pull/6219) Conflicts, might be replaced by [#6321](https://github.com/musescore/MuseScore/pull/6321) anyhow. Will check after this PR is merged.
 - [x] [#6221](https://github.com/musescore/MuseScore/pull/6221) Is a backport from master.
 - [ ] [#6227](https://github.com/musescore/MuseScore/pull/6227) Merges cleanly into master.

**Comment by MarcSabatella** [comment]
I was under the impression that steps had been / are being taken to minimize the pain of the code formatting changes, by allowing things to be automatically reformatted.  So only PR's that actually have semantic conflicts would need to be resubmitted manually.

**Comment by Jojo-Schmitz** [comment]
I'm not sure whether there is sufficient trackkeeping on which PR is needed for master too, hence this issue here. Those 165 PRs that went into 3.x is a large enough number for some of them getting lost and forgotten for master. Not all apply, some have been merged, some done differently, but there are enough left that need checking

**Comment by shoogle** [comment]
> I was under the impression that steps had been / are being taken to minimize the pain of the code formatting changes, by allowing things to be automatically reformatted. So only PR's that actually have semantic conflicts would need to be resubmitted manually.

PR #6363 has a script that does exactly this. It would be helpful if people could run it on their own PRs.

**Comment by MarcSabatella** [comment]
This still feels like something that should be possible to automate completely.  And to be perfectly frank, if it is to be done manually, it feels to me like the burden should fall on those who pushed for the change in the first place.

**Comment by anatoly-os** [comment]
95 PRs left... At least, the ones enumerated above with unticked checkboxes.
I tick the checkboxes once I manually merge corresponding PRs.

**Comment by MarcSabatella** [comment]
Thank you for taking this on!   I am certainly happy to handle any of mine that require work to rebase due to real change, but I am still hoping that the ones that can be handled more automatically can and will be.  Most of mine are small and “libmscore-y” and can wait.

**Comment by shoogle** [comment]
@anatoly-os, when merging PRs, watch out for the fact that PRs submitted before PR #6358 may show tests passing even though they have not been tested for coding style. Here's [how to tell whether they have been tested](https://github.com/musescore/MuseScore/pull/6358#issuecomment-662784569).

**Comment by anatoly-os** [comment]
85 PRs left... The ones authored by @njvdberg have been merged successfully.

**Comment by MarcSabatella** [comment]
Not merged for 3.x yet but presumably will be soon enough:

- [ ] #6391

**Comment by anatoly-os** [comment]
About 36 PRs left...

**Comment by shoogle** [comment]
A heroic effort! (I was going to do mine myself but you got there first, sorry!)

**Comment by anatoly-os** [comment]
- [ ] #5889

**Comment by SKefalidis** [comment]
#6423 is the master version of #6450 
#6451 is the master version of #6523 (not yet merged but will be soon I believe)

**Comment by jthistle** [comment]
- [ ] #6516 
- [ ] #6530

**Comment by igorkorsukov** [comment]
[] https://github.com/musescore/MuseScore/pull/6531

**Comment by Jojo-Schmitz** [comment]
* [ ] #6484
* [ ] #6546

**Comment by Jojo-Schmitz** [comment]
Is anyone continuing to work on the remaining ones?
Are there more that need to get added

**Comment by Jojo-Schmitz** [comment]
[ ] #6744 (or #6002)

**Comment by vpereverzev** [comment]
#6546 Mine is actual for 3.x only, MU4 will rely on our new network module

**Comment by Jojo-Schmitz** [comment]
OK I see, amended above

**Comment by Jojo-Schmitz** [comment]
* [ ] #6790 _(@njvdberg's master version of his PRs for 3.x)_

**Comment by Jojo-Schmitz** [comment]
* [ ] #6818 - Porting 3.5.2_backend fixes to master

**Comment by jeetee** [comment]
[] #6810 (cherry pick, libmscore only)
[] #6857 (cherry pick, libmscore only)

**Comment by Marr11317** [comment]
- [ ] #6934 : Master version of #6933 --- No measure number shown when first staff is cutaway

**Comment by MarcSabatella** [comment]
- [ ] #6899 - bad navigation after rest with content on last track

**Comment by jeetee** [comment]
- [ ] #6972 (master version of #6971) (cherry pick, libmscore only)

**Comment by Marr11317** [comment]
- [ ] #6935 - Fix #214996: show measure number interval at multi-measure rests

**Comment by Marr11317** [comment]
- [ ] #6956 bracketed accidental padding
- [ ] #6987 followup for #6935 
- [ ] #7006 vscode build

**Comment by Jojo-Schmitz** [comment]
[ ] #7044
[ ] #7084

**Comment by igorkorsukov** [comment]
* [ ] #7261 
* [ ] #7292
* [ ] #7309
* [ ] #7310

**Comment by Howard-C** [comment]
Are all portable PRs ported as of this moment?

**Comment by Jojo-Schmitz** [comment]
I think so, but would rather let @igorkorsukov and @Bootincat decide (na then close this issue)

**Comment by Tantacrul** [comment]
Closing due to inactivity and the fact that the issue is a year old. Let me know if it needs reopening.

**Comment by Jojo-Schmitz** [comment]
As far as I can tell there are still open issues, stuff that need to get ported from 3.x to master, or at least been checked vor neccessity?

**Comment by Jojo-Schmitz** [comment]
One example would be #6094 (port to maste in #11462), mentioned in the initial list, but (errnously) marked as ported, unticked now

**Comment by lvinken** [comment]
Checked the MusicXML issues still open in the Feb 15, 2021 comment: the fixes are present in master, no further work required.
