### ISSUE TITLE
MuseScore 3.5.1 Release. PRs to be merged and issues to be fixed.

### ISSUE THREAD

**Issue by anatoly-os** [musescore/MuseScore#6355]

**Comment by Jojo-Schmitz** [comment]
* [ ] #5889 - [Fix #302714](): make chord symbol playback settings available in Edit Style dialog
* [ ] #6182 - add more accidentals
* [ ] #6238 - [fix #306950](https://musescore.org/en/node/306950) - allow Ctrl+Delete from note input mode
* [ ] #6248 - Refactor score unwinding
* [ ] #6255 - partial fix for [#306911](https://musescore.org/en/node/306911)
* [ ] #6292 - Rename note Hooks to Flags, to match SMuFL terms and some more text fixes (3.x) 
* [ ] #6322 - Fix issue with en_US translation getting fed back into Transifex
* [ ] #6339 - [fix #307841](https://musescore.org/en/node/307841): crashes and more with hbox within vbox 
* [ ] #6341 - [fix #307900](https://musescore.org/en/node/307900): Crash when switching voices if notes are tied
* [ ] #6346 - [fix #307991](https://musescore.org/en/node/307991): crash when deleting all measures
* [ ] #6351 - Nashville bugs

**Comment by MarcSabatella** [comment]
Potentially #6259 (disable playback of chord symbols for older scores), if we get enough feedback to warrant it.  I'd need to update a bunch of tests.

**Comment by Jojo-Schmitz** [comment]
* [ ] #6424 - [fix #308698](https://musescore.org/en/node/308698): Continuous view stops repeats from working in playback

**Comment by Howard-C** [comment]
- [ ] #6452: Several fixes with tremolos
- [ ] #6472: Implement the third stroke style of minim-based two-note tremolos

**Comment by lvinken** [comment]
[#6485](https://github.com/musescore/MuseScore/pull/6485)

**Comment by MarcSabatella** [comment]
- [ ] #6460: add support for quality after extension (a somewhat common chord symbol that doesn't play back)

**Comment by jthistle** [comment]
- [ ] #6516: reimplement playback of articulations with single-note dynamics

^ This one was very much missed going from 3.4 -> 3.5. I hope this PR can be merged to stop the flood of complaints!

**Comment by SKefalidis** [comment]
- [ ] #6523

**Comment by jthistle** [comment]
To add to the list of regressions without fixes:

- [ ] [#301395](https://musescore.org/en/node/301395) - Single Note Dynamics: Decrescendo doesn't work on tied notes in sub-banks

**Comment by igorkorsukov** [comment]
I added who does what in the inhouse team 
https://github.com/musescore/MuseScore/issues/6355#issuecomment-671188898

**Comment by Jojo-Schmitz** [comment]
Another really big issue that needs to get looked at is the very many cases of 'no sound'.

**Comment by igorkorsukov** [comment]
fix #308978: Display language not set by Windows Language setting
I think it does not require correction, here is an explanation
https://musescore.org/en/node/308978#comment-1023940

**Comment by MarcSabatella** [comment]
There are indeed very many cases of people not having sound, but I'm not so sure there are *more* such cases with 3.5 than earlier releases.  But I am quite sure there are very many more startup crashes, with most apparently being connected to the Start Center.

**Comment by Jojo-Schmitz** [comment]
True, no sound happens frequently, but not particularly more frequent with 3.5 vs befire. Crash on startcenter though came back massively with 3.5

**Comment by MarcSabatella** [comment]
308890 (an issue with incorrect use of chord symbols) isn't a regression and not really much of a bug at all, just a case where we miss an opportunity to correct a user's error for them.

**Comment by Jojo-Schmitz** [comment]
True, not a real regression, but something that only now shows with chord symbols playback

**Comment by MarcSabatella** [comment]
It would have showed the moment you tried to transpose.  But anyhow, not really a bug either, and any fix would be a little risky, not worth it for 3.5.1.

**Comment by lvinken** [comment]
Working on [#309949](https://musescore.org/en/node/309949) and [#309950](https://musescore.org/en/node/309950), which I would like to have solved in 3.5.1.

**Comment by cbjeukendrup** [comment]
Maybe this one too: PR #6561

**Comment by lvinken** [comment]
Resolves:
Pull request [6542](https://github.com/musescore/MuseScore/pull/6542) now contains:

- [#309949](https://musescore.org/en/node/309949) [MusicXML import] guess page one credit words type
- [#309950](https://musescore.org/en/node/309950) [MusicXML import] fix title frame position
- [#310412](https://musescore.org/en/node/310412) [MusicXML import] alignment and offset of texts in vertical frames not preserved
- [#309702](https://musescore.org/en/node/309702) [MusicXML import/export] support credit-type element
- [#310678](https://musescore.org/en/node/310678) [MusicXML import] incorrect font size in title frame when credit-words size unspecified

It now solves all regressions in handling the title frame on MusicXML import that I am aware of.

**Comment by Howard-C** [comment]
#6564: [fix #310603](https://musescore.org/node/310603): tremolo customizations lost on second save/reload
This fixes a regression!

**Comment by Howard-C** [comment]
#6564: [fix #310603](https://musescore.org/node/310603): tremolo customizations lost on second save/reload

**Comment by Howard-C** [comment]
- [ ] #6564 - [fix #310603](https://musescore.org/node/310603): tremolo customizations lost on second save/reload

**Comment by lvinken** [comment]
- [ ]  [#6571](https://github.com/musescore/MuseScore/pull/6571) [fix #310570](https://musescore.org/en/node/310570) [Musicxml Export] - Triple and Quadruple Dots not exported correctly

**Comment by njvdberg** [comment]
- [ ] #6586 [Fix #309857](https://musescore.org/en/node/309857) - Divider not removed after undo of deleting a vertical frame

**Comment by ZingBlue** [comment]
Is "no sound" the same as when closing MuseScore, my audio driver breaks and plays static noises until restart?

**Comment by Jojo-Schmitz** [comment]
The above mentioned #6610 got closed, being a duplicate of #6510
