### ISSUE TITLE
MuseScore 3.5 Release. PRs to be merged and the issues to be fixed.

### ISSUE THREAD

**Issue by anatoly-os** [musescore/MuseScore#6356]
https://github.com/musescore/MuseScore/milestone/14

**Comment by Jojo-Schmitz** [comment]
Those are the milestones for 3.5.1, not for the 3.5(.0) release?

Anyhow, here's a start:

* [ ] #6345 - [Fix #307883](https://musescore.org/en/node/307883) - Key Signature appears too many times in Parts in 3.5 Beta
* [ ] #6348 - [fix #308023](https://musescore.org/en/node/308023): realize chord symbol menu command inactive
* [ ] #6350 - [Fix #307946](https://musescore.org/en/node/307946) [Fix #307945](https://musescore.org/en/node/307945) - Strange behavior with chord alignment.

**Comment by MarcSabatella** [comment]
- [ ] #6360 - https://musescore.org/en/node/308145 - missing grid in timeline

**Comment by Jojo-Schmitz** [comment]
* [ ] [#308259: 3.5RC -- Blank upload dialog on Mac](https://musescore.org/en/node/308259)

**Comment by MarcSabatella** [comment]
Recently reported and discussed, here is my PR:

- [ ] #6391 (fixes https://musescore.org/en/node/308371 - bad stem directions on tab staves)

**Comment by Jojo-Schmitz** [comment]
* [ ] #6368
