### ISSUE TITLE
MuseScore 3.6 Alpha. PRs to be merged and issues to be fixed.

### ISSUE THREAD

**Issue by Jojo-Schmitz** [musescore/MuseScore#6505]
See also https://github.com/musescore/MuseScore/milestone/15 ;-)

### PRs available:

* [x] #4824/#5853 - [Fix #127341](https://musescore.org/en/node/127341): Implements portamento for fluid
* [x] #5381 - Add Petaluma font
* [x] #5730 - Timeline optimizations
* [x] #5934 - Update Bravura to 1.39
* [ ] #5958 - [Fix #303623](https://musescore.org/en/node/303623): Fix multiple issues with chord diagrams in MusicXML export _(needs a rebase to 3.x first though)_
* [ ] #5965 - [Fix #303027](https://musescore.org/en/node/303027): Add System lines
* [x] #6182 - Add more accidentals
* [x] #6255 - partial fix for [#306911](https://musescore.org/en/node/306911)
* [x] #6292 - Rename note Hooks to Flags, to match SMuFL terms and some more text fixes
* [x] #6322 - Fix issue with en_US translation getting fed back into Transifex _(needed __before__ translations get enabled again! Got merged into 3.5.2 already)_
* [x] #6359 - Allow ledgerlines exactly as wide as the noteheads
* [x] #6398 - [Fix #97416](https://musescore.org/en/node/97416): Toggle between pitched and unpitched instruments
* [x] #6425 - [Fix #308771](https://musescore.org/en/node/308771): Migrate invisible staff lines and line color to staffType
* [x] #6431 - [Fix #308712](https://musescore.org/en/node/308712): Default button in Score Properties set to "New…"
* [x] #6470 - [Fix #153016](https://musescore.org/en/node/153016): Add mountain dulcimer and a 3-string tab preset
* [x] ~#6489 - Prepare for updated libsndfile~ _(postponed for 4.0, actually already in there)_
* [x] #6472 - Implement the third stroke style of minim-based two-note tremolos
* [ ] #6494 - [Fix #309371](https://musescore.org/en/node/309371): Ambitus for transposing instruments doesn't update when toggling concert pitch _(needs some work still)_
* [x] #6514 - Add macros for MuseScore version and revision to header/footer
* [x] #6536 - [Fix #309973](https://musescore.org/en/node/309973): Add mnemonics for Save, Save As… and Resource Manager…
* [x] #6543 - Update to latest SMuFL version 1.3
* [ ] #6550 - [Fix #277279](https://musescore.org/en/node/277279): Lack of Capabilities in the Custom Time Signature Creator (_still in Draft?)_
* [x] #6560 - Add extended fermata symbols to MusicXML I/O
* [x] #6606 - Resource "Up to date" rather than "Updated"
* [x] #6681 - [Fix #311796](https://musescore.org/en/node/311796): Crash when deleting header/footer text after hiding
* [x] #6696 - [Fix #272172](https://musescore.org/en/node/272172): Remove tuplets after inserting measures causes corruption/crash  _(apparently a 3.1 regression,)_
* [x] #6715 - [Fix #309102](https://musescore.org/en/node/309102): Dragging handle of hairpin (or other line) causes it to shoot off in the other direction
* [x] #6724 - [Fix #276840](https://musescore.org/en/node/276840): Change of soundfont is cumbersome _(May need more work? Better as is than not at all?)_
* [x] #6742 - Reduce useless whitespace in JSON files; better way to update libmscore/sym.* from SMuFL (including bugfixes)
* [x] #6743 - [Fix #257581](https://musescore.org/en/node/257581): Changes to Measure properties are not propagated between score and existing linked parts after save/reload, [fix #64636](https://musescore.org/en/node/64636): "add to measure number" is not linked between score and parts after reload
* [x] #6744 - Add support for triple sharp and triple flat
* [x] #6746 - [Fix #309040](https://musescore.org/en/node/309040): Rest auto avoidance flawed
* [x] #6747 - Merge Parnassus accidentals into MScore _(AKA Emmentaler)_, fix a couple of issues _and fix F8vb and F158vb clefs_
* [x] #6749 - [Fix #309188](https://musescore.org/en/node/309188): Doesn’t merge rests into one when the measure has 3 or 4 voices.
* [x] #6750 - Indicate pitch and on/off time in the status line
* [x] #6752 - [Fix #305613](https://musescore.org/en/node/305613): Add heavy, reverse end and heavy double barlines
* [x] #6754 - [Fix #312146](https://musescore.org/en/node/312146): "Flatten all Beams" setting ignored on reload
* [x] #6755 - Update fonts/Readme.md
* [x] #6757 - [Fix #308726](https://musescore.org/en/node/308726): Voice 1 rests collide with voice 3 rhythm slashes (above the staff)
* [x] #6775 - [Fix #312279](https://musescore.org/en/node/312279): C time signature does not update
* [x] #6789 - [Fix #312083](https://musescore.org/en/node/312083): The tempo field is not readable by screen readers
* [x] #6791 - Engraving improvements dialog
* [x] #6802 - [Fix #312442](https://musescore.org/en/node/312442): Fix palette search shortcut functionality
* [x] #6806 - [Fix #312513](https://musescore.org/en/node/312513): Add Sicilian translation
* [x] #6811 - [Fix #299196](https://musescore.org/en/node/299196) [Fix #312393 ](https://musescore.org/en/node/312393 ): Missing space between key signature and first note if time signature is hidden
* [x] #6815 - Fix freeze when tie has the same start and end note
* [x] #6817 - Porting 3.5.2_backend fixes to 3.x
* [x] #6844 - Fix sounding pitch was displayed twice due to overlapping PRs merged
* [x] #6845 - [Fix #302990](https://musescore.org/en/node/302990): Set Style Edit dialog to be non-modal to allow score traversal when showing
* [x] #6847 - [Fix #312254](https://musescore.org/en/node/312254): Add alternative choice of “To Coda”
* [x] #6853 - [Fix #312869](https://musescore.org/en/node/312869): Crash when deleting or changing a time signature in a multimeasure rest
* [x] #6855 - Fix a bug in audio export.
* [x] #6857 - [Fix #312489](https://musescore.org/en/node/312489): Harmony duration interpretation
* [x] #6856 - Various fixes for Leland
* [x] #6859 - [Fix #312854](https://musescore.org/en/node/312854): [MusicXML] musicxml from new version of Finale imports as blank sheet
* [x] #6865 - Fix some compiler warnings
* [x] #6866 - [Fix #307271](https://musescore.org/en/node/307271): [MusicXML Export] - Wrong tuplet calculation in two-note tremolo
* [x] #6867 - [Fix #259771](https://musescore.org/en/node/259771): [MusicXML] Make tremolo between notes play correct rhythm when between tuplets
* [x] #6880 - [Fix #313073](https://musescore.org/en/node/313073): InstrumentOrdering updates
* [x] #6883 - [Fix #313019](https://musescore.org/en/node/313019): Default Files in Preferences -> Score are misaligned

(Copied across from #6355)
### 3.5 Regressions with no PR yet:

* [ ] [Fix #306644](https://musescore.org/en/node/306644): Preferences window doesn't match on a 15'' Laptop screen and height isn't resizeable  @Spire42 ?
* [ ] ~[Fix #308925](https://musescore.org/en/node/308925): User velocity does nothing~
* [ ] [Fix #308975](https://musescore.org/en/node/308975): Display and editing of lines is wrong @RomanPudashkin 
* [ ] [Fix #309368](https://musescore.org/en/node/309368): Lines: when end handles are adjusted with keyboard arrows, anchor point also shifts
* [ ] #6584 - [Fix #310821](https://musescore.org/en/node/310821): Chord Symbol (Ctrl+K) on drum stave sounds as percussion _(there is a PR, but it isn't really complete)_
* [ ] [Fix #311748](https://musescore.org/en/node/311748): Updated translations don't show in MuseScore @igorkorsukov ?
* [ ] [Fix #311788](https://musescore.org/en/node/311788): There is a gap between the end of a staff (system) and the last barline (before a break), in case of a clef change to the next bar in a hidden instrument and show courtesy clef is on.
* [ ] [Fix #312029](https://musescore.org/en/node/312029): Fingering is too small on small notes / chords _(by design?)_
* [ ] [Fix #312120](https://musescore.org/en/node/312120): [Crash Reporter] error message "Host requires authentication"

### Other urgent issues with not PR yet:

* [ ] [Fix #275837](https://musescore.org/en/node/275837): MuseScore crashes during start-up while displaying "Start center" _(probably related to the below issues, at least partly, like triggered by those)_
* [ ] [Fix #310942](https://musescore.org/en/node/310942): Freezes when clicking "Copyright and download settings" in Save Online dialog _(probably a musescore.com issue)_
* [ ] [Fix #311727](https://musescore.org/en/node/311727): Can't save a score online, brings up empty dialog _(connected to the above issue)_

### Other long-time and frequent issues (where the real cause still is very unclear):

* [ ] Very many issues and forum posts of 'no sound', where sometimes [How to restore sound if playback stops working](https://musescore.org/en/node/96811) helps, but quite often not
* [ ] [Fix #271185](https://musescore.org/en/node/271185): Scores corrupted beyond repair, containing nothing but zeros

**Comment by Howard-C** [comment]
And #6529 - Remove support of "place mid-stem" option for one-note tremolos

**Comment by njvdberg** [comment]
- [ ] [#6479](https://github.com/musescore/MuseScore/pull/6479) - Automatic score ordering and bracketing
- [ ] [#6538](https://github.com/musescore/MuseScore/pull/6538) - Algorithm for spreading staves/systems over a page

**Comment by cbjeukendrup** [comment]
This one too?
- [ ] #6593 - Restructure Palettes buttons and add "Expand/Collapse All" buttons
(Involves some string translation.)

**Comment by Jojo-Schmitz** [comment]
Other long-time and frequent issues:

* [ ] Very many issues and forum posts of 'no sound', where sometimes https://musescore.org/en/faq#faq-301733 helps, but quite often not
* [ ] [fix #271185](https://musescore.org/en/node/271185): Scores corrupted beyond repair, containing nothing but zeros

3.5 Regressions with no PR yet:

* [ ] [fix #306644](https://musescore.org/en/node/306644): Preferences window doesn't match on a 15'' Laptop screen and height isn't resizeable  @Spire42 ?
* [ ] [fix #308726](https://musescore.org/en/node/308726): Voice 1 rests collide with voice 3 rhythm slashes (above the staff)
* [ ] [fix #308925](https://musescore.org/en/node/308925): User velocity does nothing
* [ ] [fix #308975](https://musescore.org/en/node/308975): Display and editing of lines is wrong @RomanPudashkin 
* [ ] [fix #309040](https://musescore.org/en/node/309040): Rest auto avoidance flawed  @tobik ?
* [ ] [fix #309102](https://musescore.org/en/node/309102): Dragging handle of hairpin (or other line) causes it to shoot off in the other direction
* [ ] [fix #309188](https://musescore.org/en/node/309188): Doesn’t merge rests into one when the measure has 3 or 4 voices.  @tobik ?
* [ ] [fix #309368](https://musescore.org/en/node/309368): Lines: when end handles are adjusted with keyboard arrows, anchor point also shifts

**Comment by MarcSabatella** [comment]
Thanks for staying on top of this, @Jojo-Schmitz !  A couple of notes:

- I don't think https://musescore.org/en/node/308925 is actually a recent regression; I think the OP was confused when they reported it worked in 3.4.  As far as I know, velocity has been irrelevant for SND instruments ever since SND became a thing.  @jthistle can perhaps clarify

- All the issues involving rest position are related, and to some extent are the expected results of changing layout in ways that makes some cases better, others worse.  Probably these cases need to be addressed one by one.  While the regression in unfortunate, 3.6 does seem like a good time to look again.

- The two line issues are also related, connected to the new line dragging functionality, and should also be addressed together.

**Comment by Jojo-Schmitz** [comment]
I'll take https://musescore.org/en/node/308925 off the list once confirmed that this isn't an issue

**Comment by Howard-C** [comment]
#6732 - Change tremolo-related names & strings

**Comment by Jojo-Schmitz** [comment]
* [ ] #6724 - [Fix #276840](https://musescore.org/en/node/276840): Change of soundfont is cumbersome _(May need more work?)_

**Comment by Jojo-Schmitz** [comment]
* [ ] ##6743 - [Fix #257581](https://musescore.org/en/node/257581): Changes to Measure properties are not propagated between score and existing linked parts after save/reload, [fix #64636](https://musescore.org/en/node/64636): "add to measure number" is not linked between score and parts after reload

**Comment by Jojo-Schmitz** [comment]
* [ ] #6002 - Add support for triple sharp and triple flat _(needs a rebase, @mattmcclinch?)_

**Comment by Jojo-Schmitz** [comment]
* [ ] #6746 - [Fix #309040](https://musescore.org/en/node/309040): Rest auto avoidance flawed

**Comment by Jojo-Schmitz** [comment]
* [ ] #6742 - Improve font rendering
* [ ] #6747 - Merge Parnassus accidentals into MScore and fix a couple of issues

**Comment by Jojo-Schmitz** [comment]
* [ ] 6749 - [Fix #309188](https://musescore.org/en/node/309188): Doesn’t merge rests into one when the measure has 3 or 4 voices.

**Comment by Jojo-Schmitz** [comment]
* [ ] #6750 - Indicate pitch and on/off time in the status line

**Comment by Jojo-Schmitz** [comment]
* [ ] #6752 - [Fix #305613](https://musescore.org/en/node/305613): Add heavy, reverse end and heavy double barlines

**Comment by Jojo-Schmitz** [comment]
* [ ] #6754 - [Fix #312146](https://musescore.org/en/node/312146): "Flatten all Beams" setting ignored on reload

**Comment by Jojo-Schmitz** [comment]
* [ ] #6757 - [Fix #308726](https://musescore.org/en/node/308726): Voice 1 rests collide with voice 3 rhythm slashes (above the staff)

**Comment by Jojo-Schmitz** [comment]
[ ] #6744 (or # #6002)

**Comment by mirabilos** [comment]
[ ] #6759 - honour symbol advance width from font when drawing accidentals (improve font rendering)

This was originally part of #6742 but I split it off because ① #6759 corresponds to MU4 #6748 (which was merged into master todat) and ② #6742 now mostly deals with JSON/SMuFL topics only, for better separation of concerns, and because #6759 can basically be merged as-is.

**Comment by jeetee** [comment]
- [ ] #6810 - fix duplicate voltas leads to ignoring following voltas

**Comment by psmokotnin** [comment]
Please change #6809 with #6815

**Comment by Jojo-Schmitz** [comment]
done

**Comment by lvinken** [comment]
- [ ] [#6834](https://github.com/musescore/MuseScore/pull/6834) correct MusicXML import of changed transpositions

**Comment by lvinken** [comment]
- [ ] [6869](https://github.com/musescore/MuseScore/pull/6869) fix #312714: [Musicxml Export] - Hairpin export stops halfway

**Comment by vpereverzev** [comment]
No more merges for 3.6 alpha, remaining PRs (basicly WIP) will be merged in 3.6 beta)

@Jojo-Schmitz TY very much for this accounting of pull requests, it helps a lot

**Comment by Jojo-Schmitz** [comment]
Should we rename this issue to "MuseScore 3.6 Alpha". PRs to be merged and issues to be fixed.", close it and start a new for Beta/Release?

**Comment by vpereverzev** [comment]
Yes, it makes sense
