### ISSUE TITLE
MuseScore 3.5.2 Release. PRs to be merged and issues to be fixed.

### ISSUE THREAD

**Issue by Jojo-Schmitz** [musescore/MuseScore#6669]
* [x] #6322 - Fix issue with en_US translation getting fed back into Transifex _(needed __before__ translations get enabled again, so latest in 3.6!)_
* [ ] #6560 - Add extended fermata symbols to MusicXML I/O _(not really a regression, therefor might get postponed to 3.6)_
* [x] #6651 - Fixed unexpected geometry stretching in "Edit style" dialog
* [x] #6653 - [Fix #311520](https://musescore.org/en/node/311520): Harmony playback preferences not honored until toggled
* [x] #6665 - [Fix #311621](https://musescore.org/en/node/311621): Fix export audio on Windows
* [x] #6667 - [Fix #311661](https://musescore.org/en/node/311661): Fix potential crash in `PianoView::updateNotes()` _(not really a regression though)_
* [ ] #6681 - [Fix #311796](https://musescore.org/en/node/311796): Crash when deleting header/footer text after hiding _(3.5(.0) regression, therefor might get postponed to 3.6?)_

### 3.5.1 Regressions with no PR or fix yet:

* [ ] [Fix #311516](https://musescore.org/en/node/311516): False or old link when downloading the latest version 3.5.1 _(website issue)_
* [ ] [Fix #311526](https://musescore.org/en/node/311526): Automatic downloading failed for Windows portable version _(website issue)_
* [x] [Fix #311695](https://musescore.org/en/node/311695): Edits to system text/tempo marking after save and reload of score do not propagate to all parts.  @njvdberg ?
* [ ] [Fix #311748](https://musescore.org/en/node/311748): Updated translations don't show in MuseScore

### 3.5(.0) Regressions with no PR yet:

* [ ] [Fix #306644](https://musescore.org/en/node/306644): Preferences window doesn't match on a 15'' Laptop screen and height isn't resizeable  @Spire42 ?
* [ ] [Fix #308726](https://musescore.org/en/node/308726): Voice 1 rests collide with voice 3 rhythm slashes (above the staff)
* [ ] ~[Fix #308925](https://musescore.org/en/node/308925): User velocity does nothing~
* [ ] [Fix #308975](https://musescore.org/en/node/308975): Display and editing of lines is wrong @RomanPudashkin 
* [ ] [Fix #309040](https://musescore.org/en/node/309040): Rest auto avoidance flawed  @tobik ?
* [ ] [Fix #309102](https://musescore.org/en/node/309102): Dragging handle of hairpin (or other line) causes it to shoot off in the other direction
* [ ] [Fix #309188](https://musescore.org/en/node/309188): Doesn’t merge rests into one when the measure has 3 or 4 voices.  @tobik ?
* [ ] [Fix #309368](https://musescore.org/en/node/309368): Lines: when end handles are adjusted with keyboard arrows, anchor point also shifts

### Other long-time and frequent issues (where the real cause still is very unclear):

* [ ] Very many issues and forum posts of 'no sound', where sometimes [How to restore sound if playback stops working](https://musescore.org/en/node/96811), but quite often not
* [ ] [Fix #271185](https://musescore.org/en/node/271185): Scores corrupted beyond repair, containing nothing but zeros
