### ISSUE TITLE
MuseScore 3.6 Beta/RC/Release. PRs to be merged and issues to be fixed. 

### ISSUE THREAD

**Issue by Jojo-Schmitz** [musescore/MuseScore#6887]
See also https://github.com/musescore/MuseScore/milestone/15 ;-)

### PRs available:

* [x] ~#4476 - [Fix #280504](https://musescore.org/en/node/280504): Edit surrogate pairs atomically _(needs a rebase to 3.x first though)_~
* [ ] #4853 - [Fix #286900](https://musescore.org/en/node/286900): MIDI input menu has no None option
* [x] ~#5071 - [Fix #288968](https://musescore.org/en/node/288968): Add adjusted bar numbers to the status bar, if they differ _(needs a rebase to 3.x first though)_~
* [x] ~#5122 - Improve text editing appearance on score _(needs a rebase to 3.x first though)_~
* [x] #5568 - [Fix #295020](https://musescore.org/en/node/295020): Range-transpose shortcuts _(got manually merged into 3.x)_
* [x] ~#5571 - Add Brassband genre _(needs a rebase though)_~
* [x] ~#5816 - [Fix #280260](https://musescore.org/en/node/280260): Added an option to set the default font for all text types~ _(for master, 3.x version now in #7127)_
* [x] ~#5958 - [Fix #303623](https://musescore.org/en/node/303623): Fix multiple issues with chord diagrams in MusicXML export _(needs a rebase to 3.x first though)_~
* [x] #5965 - [Fix #303027](https://musescore.org/en/node/303027): Add System lines
* [x] #6349 - [Fix #270337](https://musescore.org/en/node/270337): True dotted lines
* [x] ~#6375 - [Fix #303426](https://musescore.org/en/node/303426): Editable elements still edited after entering Note Entry mode _(rebase to 3.x needed)_~
* [x] #6392 - MinGW mtests on Windows with QtCreator
* [x] #6422 - [Fix #295722](https://musescore.org/en/node/295722): Allow changing staff visibility mid-score
* [x] #6461 - [Fix #281639](https://musescore.org/en/node/281639): Better handling of Clefs, Barlines on ossias and cutaway
* [ ] #6494 - [Fix #309371](https://musescore.org/en/node/309371): Ambitus for transposing instruments doesn't update when toggling concert pitch _(needs some work still)_
* [x] ~#6517 - Large Time Signatures (_still in draft though)_~
* [x] #6524 - [Fix #300340](https://musescore.org/en/node/300340): Additive Time Signatures Do Not Appear Properly in the Gonville Font _(#6517, #6550 and #6917 do contain this one fully though)_
* [ ] #6550 - [Fix #277279](https://musescore.org/en/node/277279): Lack of Capabilities in the Custom Time Signature Creator
* [x] #6584 - [Fix #310821](https://musescore.org/en/node/310821): Chord Symbol (Ctrl+K) on drum stave sounds as percussion
* [ ] #6693 - [Fix #311792](https://musescore.org/en/node/311792): Override alter tag with note tuning value if present
* [x] #6826 - [Fix #312608](https://musescore.org/en/node/312608): Stems too short on chords outside staff
* [x] #6858 - [Fix #312959](https://musescore.org/en/node/312959): Implement New Navigation Commands (Frames/Sections/Playback Cursor)
* [x] #6886 - Supply a pre-3.6-default style file
* [x] #6888 - [Fix #313105](https://musescore.org/en/node/313105): "No chord" MusicXML import
* [x] #6889 - Porting some master changes/PRs (#5566, #6442) to 3.x
* [x] #6894 - Score symbols bounding boxes
* [x] #6899 - [Fix #313323](https://musescore.org/en/node/313323): Bad navigation after rest with content on last track
* [x] #6909 - [Fix #313428](https://musescore.org/en/node/313428): Mandolin has Grand Piano sound
* [x] #6913 - Fixed data corruption after using zita reverb (CLI mode) _(cherry-pick from 3.5.2_backend)_
* [ ] #6917 - Paren time sig _(needs #6550 first)_
* [x] #6928 - [Fix #313195](https://musescore.org/en/node/313195): Add Synalepha shortcut
* [x] #6935 - Add an option to show measure number interval at mmrests _(still in draft though)_
* [x] #6952 - [Fix #312120](https://musescore.org/en/node/312120): [Crash Reporter] error message "Host requires authentication"
* [x] #6955 - [Fix #292387](https://musescore.org/en/node/292387): [MusicXML] Drumset of MusicXML sounds pitch
* [x] #6956 - Acc padding
* [x] #6958 - [Fix #312195](https://musescore.org/en/node/312195): Style dialog loses setting of chord symbol radio buttons and fix tab order in Edit Style dialog and [Fix #306644](https://musescore.org/en/node/306644): Preferences window doesn't match on a 15'' Laptop screen and height isn't resizeable
* [x] #6968 - [Fix #86376](https://musescore.org/en/node/86376), [fix #313736](https://musescore.org/en/node/313736): Additions to F2 Special Characters > Common Symbols
* [x] #6971 - [Fix #313751](https://musescore.org/en/node/313751): Jump at Volta End makes last measure not skipped and [Fix #313772](https://musescore.org/en/node/313772): Final playthrough after Jump not reset for next section
* [x] #6973 - [Fix #313771](https://musescore.org/en/node/313771): Switching instruments from an instrument with tabulature in a linked staff to one that does not support tablature causes crash
* [x] #6999 - Fix typo (this score just doesn't exist, with that name) 
* [x] #7000 - [Fix #313857](https://musescore.org/en/node/313857): Fractional font sizes can't be input using the "Preferences" dialog
* [x] #7001 - [Fix #313420](https://musescore.org/en/node/313420): [MusicXML] Instrument brackets are all imported at column 0
* [ ] #7003 - [Fix #310158](https://musescore.org/en/node/310158): Don't null terminate MIDI sequence track name messages
* [x] #7004 - [Fix #311039](https://musescore.org/en/node/311039): Let fretboard diagrams include open strings with multiple dots
* [x] #7005 - [Fix #313926](https://musescore.org/en/node/313926): Correct focus-in problem when a dialog box is open
* [x] #7006 - Allow windows build with vscode
* [x] #7015 - [Fix #313896](https://musescore.org/en/node/313896): Portamento playdown not working
* [x] #7016 - Leland style values update
* [x] #7019 - [Fix #313886](https://musescore.org/en/node/313886): Streamline user experience regarding Export
* [x] #7020 - c-splashscreen of 3.6
* [x] #7022 - [Fix #279707](https://musescore.org/en/node/279707): Command line option to update AppImage
* [x] #7024 - Clean and fix ZitaReverb
* [x] #7026 - [Fix #288098](https://musescore.org/en/node/288098), [#307301](https://musescore.org/en/node/307301), [#305958](https://musescore.org/en/node/305958), [#295629](https://musescore.org/en/node/295629): Interactions between breaks and frames
* [x] #7027 - [Fix #302427](https://musescore.org/en/node/302427): Export breaths after rests in MusicXML
* [x] #7032 - update/fix mtest after PR #7001
* [x] #7033 - Mountain Dulcimer Updates
* [x] #7036 - [Fix #314029](https://musescore.org/en/node/314029): Order of Text styles in Inspector dropdown and Styles dialog is different
* [x] #7037 - [Fix #18038](https://musescore.org/en/node/18038): Change checkboxes to radio buttons for transpose dialog and page style groupboxes
* [x] #7041 - [Fix #229546](https://musescore.org/en/node/229546): [MusicXML] Clef change export/import in MusicXML switches side of barline
* [x] #7042 - [Fix #313704](https://musescore.org/en/node/313704): Crash generating parts with text/hbo/vbox
* [x] #7044 - [Fix #305555](https://musescore.org/en/node/305555): Add cut2 and cut3 time signatures to master palette
* [x] #7048 - Fix vtests
* [x] #7050 - Fix stem length of notes with mirrored notehead
* [x] #7051 - Make maximum zoom limit bigger
* [x] #7052 - Update pre-3.6 style defaults for bracketed accidentals and column alignment
* [x] #7053 - [Fix #9720](https://musescore.org/en/node/9720): Fix build breaks when OMR is enabled and prevent crash when importing a PDF with no staff
* [x] #7054 - Temporarily disable Save to Cloud option for Beta release
* [x] #7056 - Update mtest after spatium change.
* [x] #7059 - [Fix #314235](https://musescore.org/en/node/314235): Size, Font and Style for glissando text get lost on save
* [x] #7064  - Fix shadow note ledger lines and stem length
* [x] #7066  - Fix compiler warnings
* [x] #7072  - New Icons for Palettes, Dock Widgets and Tab Bar
* [x] #7076  - Don't show empty Inspector for System- and Page break nor for non-tab and non-half note tremolos between notes
* [x] #7077 - [Fix #314272](https://musescore.org/en/node/314272): Edit Text Style Name fails for User-7 and higher
* [x] #7079 - Document initial versions for the recently added plugin API properties
* [x] #7084 - [Fix #314246](https://musescore.org/en/node/314246): Some dialogs (under MacOS) have the Cancel and OK buttons reversed, right to left.
* [x] #7085 - [Fix #313946](https://musescore.org/en/node/313946): MusicXML import should honor "measure-style/slash"
* [x] #7088 - Update fonttools/smufl2sym-in-trans.json _(follow up for #7044)_
* [x] #7093 - Enable Ctrl+Shift+# to add a sharp for some non-US keyboards
* [x] #7094 - Remove (the commented out) mtest for cut2 and cut3 timesigs  _(follow up for #7044)_
* [x] #7099 - Enable Ctrl+Shift+# to add a sharp for some more non-US keyboards _(follow up to #7093)_
* [x] #7110 - fix https://trello.com/c/P9b373re/73-atonal-key-signature-causes-spacing-issues
* [x] #7118 - Fix printing user errors in musescore.cpp
* [x] #7122 - Center Score in Score View when opening a score
* [x] #7126 - Avoid deprecated assignment past the end of QString
* [x] #7127 - [Fix #280260](https://musescore.org/en/node/280260): Added an option to set the default font for all text types _(counterpart of #5816, which is for master)_
* [x] #7132 - [Fix #314551](https://musescore.org/en/node/314551): Duplicate check of identical expression
* [x] #7136 - Fix compiler warning reg. duplicate name and unused variable
* [x] #7141 - [Fix #314633](https://musescore.org/en/node/314633): Inconsistent stem directions on middle-line beamed notes
* [x] #7143 - [Fix #314655](https://musescore.org/en/node/314655): Avoid spaces and more when exporting files
* [x] #7145 - [Fix #286153](https://musescore.org/en/node/286153): Check box "Show MIDI controls in mixer" in Preferences/Score page has no effect
* [x] #7146 - Remove Leland.mss from Preferences
* [x] #7147 - Fix https://trello.com/c/P9b373re - bad start point for continued lines
* [ ] #7148 - [Fix #314665](https://musescore.org/en/node/314665): Don't force "long" slurs above the staff _(questionable whether we'd want this in 3.6)_
* [x] #7151 - [Fix #314687](https://musescore.org/en/node/314687): Identical condition checked twice
* [x] #7155 - [Fix #314696](https://musescore.org/en/node/314696): Ties end at wrong note
* [x] #7161 - Cleanup translatable texts 
* [x] #7167 - [Fix #303623](https://musescore.org/en/node/303623): Fix multiple issues with chord diagrams in MusicXML export _(rebase of #5958)_
* [x] #7187 - Fixes for translatable texts
* [x] #7190 - [Fix #314696](https://musescore.org/en/node/314696): Ties end at wrong note _(Take 2)_
* [x] #7199 - Translatable texts fixes
* [x] #7200 - [Fix #314642](https://musescore.org/en/node/314642): [MusicXML] big 32nd tuplet exports wrong durations
* [x] #7201 - [Fix #315002](https://musescore.org/en/node/315002): Prevent potential crash
* [x] #7202 - Filter unused "customised" score orders.
* [x] #7203 - [Fix #315106](https://musescore.org/en/node/315106): Show 2 decimals for Tempo in Play Panel

### 3.5+ Regressions with no PR yet:
(Copied across from #6505)

* [ ] ~[Fix #308925](https://musescore.org/en/node/308925): User velocity does nothing~
* [ ] [Fix #308975](https://musescore.org/en/node/308975): Display and editing of lines is wrong @RomanPudashkin 
* [x] [Fix #311748](https://musescore.org/en/node/311748): Updated translations don't show in MuseScore @igorkorsukov ?
* [ ] [Fix #311788](https://musescore.org/en/node/311788): There is a gap between the end of a staff (system) and the last barline (before a break), in case of a clef change to the next bar in a hidden instrument and show courtesy clef is on.
* [ ] [Fix #312029](https://musescore.org/en/node/312029): Fingering is too small on small notes / chords _(by design?)_
* [x] [Fix #313253](https://musescore.org/en/node/313253): Tablature SVG export

### Other urgent issues or earlier regressions with no PR yet:

* [ ] [Fix #275837](https://musescore.org/en/node/275837): MuseScore crashes during start-up while displaying "Start center" _(probably related to the below issues, at least partly, like triggered by those)_
* [ ] [Fix #310942](https://musescore.org/en/node/310942): Freezes when clicking "Copyright and download settings" in Save Online dialog _(probably a musescore.com issue)_
* [ ] [Fix #311727](https://musescore.org/en/node/311727): Can't save a score online, brings up empty dialog _(connected to the above issue)_
* [ ] [Fix #313298](https://musescore.org/en/node/313298): MuseScore in Microsoft Store is outdated
* [ ] [Fix #313840](https://musescore.org/en/node/313840): Issue with saving score online when using "Upload score audio" (and a custom soundfont)

### Other long-time and frequent issues (where the real cause still is very unclear):

* [ ] Very many issues and forum posts of 'no sound', where sometimes [How to restore sound if playback stops working](https://musescore.org/en/node/96811) helps, but quite often not
* [ ] [Fix #271185](https://musescore.org/en/node/271185): Scores corrupted beyond repair, containing nothing but zeros

**Comment by cbjeukendrup** [comment]
- [ ] #6885 - New Export dialog

**Comment by ypoissant** [comment]
[#6868 - Add Ease in and ease out to all glissandi styles](https://github.com/musescore/MuseScore/pull/6868)

**Comment by worldwideweary** [comment]
#6547 - Updates Select Similar Beat. Goes hand-in-hand with the split measure update that was merged
#6680 - Updates glissandos for tab, but has yet to be reviewed for a vtest change
#6695 - Updates on-screen keyboard when issuing chromatic transposition command shortcut upon range

**Comment by Howard-C** [comment]
- [ ] #5731

**Comment by Jojo-Schmitz** [comment]
Would be good if y'all would add a) the checkbox (as `* [ ]`) and b) a link to the issue(s) the PR is solving

**Comment by vpereverzev** [comment]
> Would be good if y'all would add a) the checkbox (as `* [ ]`) and b) a link to the issue(s) the PR is solving, if any

@ypoissant @worldwideweary please, update your links

**Comment by njvdberg** [comment]
- [ ] #6891 - Improves recognition of instrument when loading a pre-3.6 score

**Comment by elerouxx** [comment]
* [ ] #6376

**Comment by elerouxx** [comment]
- [ ] #6376 - Fix 308242: Elements that need fixing with Staff Type Changes

**Comment by njvdberg** [comment]
- [ ] #6920 - Added missing family definitions.

**Comment by Marr11317** [comment]
- [ ] #6933 - fix #313524 measure numbers not showing when first staff is cutaway

**Comment by shoogle** [comment]
- [ ] PR #6919 - [MU3] Partial fix #279707: First steps towards automatic updates on Linux

**Comment by njvdberg** [comment]
- [ ] -#6938 - [MU3] Update Vertical Staff Spreading

**Comment by Marr11317** [comment]
- [ ] - #6935 - show measure number interval at multi-measure rests

**Comment by MarcSabatella** [comment]
- [ ] #6954 - style dialog loses setting of chord symbol radio buttons

**Comment by njvdberg** [comment]
- [ ] #6979 - MU3] Use instrumentId in instrument-famiy override instead of old trackName.

**Comment by njvdberg** [comment]
- [ ] #6982 - [MU3] Update templates

**Comment by Howard-C** [comment]
- [ ] #6989 - Clean-up Page page of Styles and fix tabstops

**Comment by njvdberg** [comment]
- [ ] #6995 - [MU3] Solve sorting bug which reverse the sorting order for every sort.

**Comment by Jojo-Schmitz** [comment]
* [ ] #6999 - Fix typo (this score just doesn't exist, with that name) 
* [ ] #7000 - [Fix #313857](https://musescore.org/en/node/313857): Fractional font sizes can't be input using the "Preferences" dialog

**Comment by Jojo-Schmitz** [comment]
* [ ] #7001 - [Fix #313420](https://musescore.org/en/node/313420): [MusicXML] Instrument brackets are all imported at column 0

**Comment by Jojo-Schmitz** [comment]
* [ ] #7005 - [Fix #313926](https://musescore.org/en/node/313926): Correct focus-in problem when a dialog box is open

**Comment by Jojo-Schmitz** [comment]
* [ ] #7004 - [Fix #311039](https://musescore.org/en/node/311039): Let fretboard diagrams include open strings with multiple dots

**Comment by Jojo-Schmitz** [comment]
* [ ] #6888 - [Fix #313105](https://musescore.org/en/node/313105): "No chord" MusicXML import

**Comment by Jojo-Schmitz** [comment]
* [ ] #6693 - [Fix #311792](https://musescore.org/en/node/311792): Override alter tag with note tuning value if present

**Comment by Jojo-Schmitz** [comment]
* [ ] #7015 - [Fix #313896](https://musescore.org/en/node/313896): Portamento playdown not working

**Comment by Jojo-Schmitz** [comment]
* [ ] #7019 - [Fix #313886](https://musescore.org/en/node/313886): Streamline user experience regarding Export

**Comment by ypoissant** [comment]
-[ ] [#7021](https://github.com/musescore/MuseScore/pull/7021) - [MU3] Fix #313960 Portamento starts on wrong pitch

**Comment by Jojo-Schmitz** [comment]
* [ ] #7022 - [Fix #279707](https://musescore.org/en/node/279707): Command line option to update AppImage

**Comment by Jojo-Schmitz** [comment]
* [ ] #6956 - Acc padding

**Comment by Jojo-Schmitz** [comment]
* [ ] #7020 - c-splashscreen of 3.6
* [ ] #7024 - Clean and fix ZitaReverb

**Comment by Jojo-Schmitz** [comment]
* [ ] #7003 - [Fix #310158](https://musescore.org/en/node/310158): Don't null terminate MIDI sequence track name messages

**Comment by Jojo-Schmitz** [comment]
* [ ] #7026 - [Fix #288098](https://musescore.org/en/node/288098), [#307301](https://musescore.org/en/node/307301), [#305958](https://musescore.org/en/node/305958), [#295629](https://musescore.org/en/node/295629): Interactions between breaks and frames
* [ ] #7027 - [Fix #302427](https://musescore.org/en/node/302427): Export breaths after rests in MusicXML

**Comment by Jojo-Schmitz** [comment]
* [ ] #6826 - [Fix #312608](https://musescore.org/en/node/312608): Stems too short on chords outside staff

**Comment by Jojo-Schmitz** [comment]
* [ ] #7032 - update/fix mtest after PR #7001
* [ ] #7033 - Mountain Dulcimer Updates

**Comment by Jojo-Schmitz** [comment]
* [ ] #7035 - [Fix #314029](https://musescore.org/en/node/314029): Order of Text styles in Inspector dropdown and Styles dialog is different
* [ ] #4853 - [Fix #286900](https://musescore.org/en/node/286900): MIDI input menu has no None option

**Comment by Jojo-Schmitz** [comment]
#7037 - Fix #18038: Change checkboxes to radio buttons for transpose dialog and page style groupboxes

**Comment by Jojo-Schmitz** [comment]
* [ ] #7041 - [Fix #229546](https://musescore.org/en/node/229546): [MusicXML] Clef change export/import in MusicXML switches side of barline
* [ ] #7042 - [Fix #313704](https://musescore.org/en/node/313704): Crash generating parts with text/hbo/vbox

**Comment by Jojo-Schmitz** [comment]
* [ ] #7044 - [Fix #305555](https://musescore.org/en/node/305555): Add cut2 and cut3 time signatures to master palette

**Comment by MarcSabatella** [comment]
- [ ] #7026 - [Fix #288098](https://musescore.org/en/node/288098): Long instrument names appear in first system after vertical frame

**Comment by Jojo-Schmitz** [comment]
> * [ ]  #7026 - [Fix #288098](https://musescore.org/en/node/288098): Long instrument names appear in first system after vertical frame

That had been added already to the initial post ;-)

**Comment by Jojo-Schmitz** [comment]
* [ ] #7048 - Fix vtests
* [ ] #7050 - Fix stem length of notes with mirrored notehead

**Comment by MarcSabatella** [comment]
- [ ] #7043 - improve collision avoidance between accidentals and ledger lines

**Comment by Jojo-Schmitz** [comment]
* [ ] #7051 - Make maximum zoom limit bigger
* [ ] #7052 - Update pre-3.6 style defaults for bracketed accidentals and column alignment
* [ ] #7053 - [Fix #9720](https://musescore.org/en/node/9720): Fix build breaks when OMR is enabled and prevent crash when importing a PDF with no staff

**Comment by Jojo-Schmitz** [comment]
* [ ] #7054 - Temporarily disable Save to Cloud option for Beta release

**Comment by njvdberg** [comment]
- [ ] #7055 - [MU3] Labeling solo parts

**Comment by Jojo-Schmitz** [comment]
* [ ] #7056 - Update mtest after spatium change.

**Comment by Jojo-Schmitz** [comment]
* [ ] #7059 - [Fix #314235](https://musescore.org/en/node/314235): Size, Font and Style for glissando text get lost on save

**Comment by MarcSabatella** [comment]
- [ ] #7067 - further improvements in accidental / ledger line avoidance (fixes a slight regression in #7043 )

**Comment by Jojo-Schmitz** [comment]
* [ ] #7064  - Fix shadow note ledger lines and stem length
* [ ] #7066  - Fix compiler warnings
* [ ] #7072  - New Icons for Palettes, Dock Widgets and Tab Bar

**Comment by Jojo-Schmitz** [comment]
* [ ] #7076  - Don't show empty Inspector for System- and Page break nor for non-tab and non-half note tremolos between notes

**Comment by Jojo-Schmitz** [comment]
* [ ] #7077 - [Fix #314272](https://musescore.org/en/node/314272): Edit Text Style Name fails for User-7 and higher

**Comment by Marr11317** [comment]
- [ ] #7083 : [Plugins] add ability to get score path from score object.

**Comment by Jojo-Schmitz** [comment]
* [ ] #7079  - Document initial versions for the recently added plugin API properties

**Comment by njvdberg** [comment]
- [ ] #7090 - [MU3] Spacer issue

**Comment by MarcSabatella** [comment]
- [ ] #7091 - Fix 277756 - [No kerning for MuseJazzText](https://musescore.org/en/node/277756)

**Comment by elerouxx** [comment]
> * [ ]  #6461  - [Fix #281639: ](https://musescore.org/en/node/281639) Better handling of Clefs, Barlines on ossias and cutaway

**Comment by Jojo-Schmitz** [comment]
> > * [ ]   #6461  - [Fix #281639: ](https://musescore.org/en/node/281639) Better handling of Clefs, Barlines on ossias and cutaway

Mentioned in the initial post too...

And
* [ ] #7092 - Fix systems jumping down page on every edit

**Comment by njvdberg** [comment]
> > * [ ]   #6461  - [Fix #281639: ](https://musescore.org/en/node/281639) Better handling of Clefs, Barlines on ossias and cutaway

This PR is  actually doing the same as PR #7090

**Comment by Jojo-Schmitz** [comment]
I guess you meant #7091?

**Comment by Jojo-Schmitz** [comment]
* [ ] #5816 - [Fix #280260](https://musescore.org/en/node/280260): Added an option to set the default font for all text types _(needs a rebase (to 3.x) though)_

**Comment by Howard-C** [comment]
- [ ] #7101 - Add demo score "Dawn"

**Comment by Asmatzaile** [comment]
[ * ] #7105 - Fix #313195: enable the synalepha shortcut in lyrics edit mode

**Comment by njvdberg** [comment]
- [ ] #7124 - [MU3] Solve brace scaling issues

**Comment by Jojo-Schmitz** [comment]
* [ ] #7110 - fix https://trello.com/c/P9b373re/73-atonal-key-signature-causes-spacing-issues
* [ ] #7118 - Fix printing user errors in musescore.cpp
* [ ] #7121 - [Fix #314149](https://musescore.org/en/node/314149): Order of buttons in ScoreMigrationDialog platform specific 
* [ ] #7122 - Center Score in Score View when opening a score

**Comment by Jojo-Schmitz** [comment]
* [ ] #7126 - Avoid deprecated assignment past the end of QString
* [ ] #7127 - [Fix #280260](https://musescore.org/en/node/280260): Added an option to set the default font for all text types

**Comment by elerouxx** [comment]
* [ ]  #7131 - Improved code to avoid MinGW compiler warnings introduced in #6461

**Comment by Jojo-Schmitz** [comment]
* [ ] #7132 - [Fix #314551](https://musescore.org/en/node/314551): Duplicate check of identical expression
* [ ] #7136 - Fix compiler warning reg. duplicate name

**Comment by Howard-C** [comment]
- [ ] #7134 - Add some missing slurs (to _Dawn_)

**Comment by Howard-C** [comment]
- [ ] #7140 - Fix page margins and adjust layout (unfortunately...)

**Comment by Jojo-Schmitz** [comment]
* [ ] #7143 - [Fix #314655](https://musescore.org/en/node/314655): Avoid spaces and more when exporting files
* [ ] #7145 - [Fix #286153](https://musescore.org/en/node/286153): Check box "Show MIDI controls in mixer" in Preferences/Score page has no effect
* [ ] #7146 - Remove Leland.mss from Preferences

**Comment by Jojo-Schmitz** [comment]
* [ ] #7141 - [Fix #314633](https://musescore.org/en/node/314633): Inconsistent stem directions on middle-line beamed notes
* [ ] #7147 - Fix https://trello.com/c/P9b373re - bad start point for continued lines
* [ ] #7148 - [Fix #314665](https://musescore.org/en/node/314665): Don't force "long" slurs above the staff

**Comment by Jojo-Schmitz** [comment]
* [ ] #7155 - [Fix #314696](https://musescore.org/en/node/314696): Ties end at wrong note

**Comment by MarcSabatella** [comment]
FWIW, #7148 is on the list above, but to me it's not a given that we want it for 3.6.  It's the right thing to do from an engraving perspective, but we do need to consider how big of an effect it might have on existing scores.

**Comment by Jojo-Schmitz** [comment]
* [ ] #7161 - Cleanup translatable texts

**Comment by lvinken** [comment]
- [ ] [#7171](https://github.com/musescore/MuseScore/pull/7171) - import MusicXML tempo changes without explicit text to display as invisible and prevent duplicate tempo changes

This is requested by the [Music21](http://web.mit.edu/music21/) project to improve the way MuseScore displays their MusicXML.

**Comment by MarcSabatella** [comment]
- [ ] #7176 - fixes a number of issues (some long-standing, some regressions) with line dragging behavior

**Comment by njvdberg** [comment]
- [ ] #7181 - Fix #314335 - System line disappears with top instrument

**Comment by MarcSabatella** [comment]
Two fixes having to do with scaling of elements.

This one fixes a regression introduced in 3.5 and seems simple and safe
- [ ] #7195 - don't scale fingering with note size

This one needs more review and perhaps an alternate solution could be proposed, but one or another this needs to be addressed before release:
- [ ] #7192 - fix measure numbers colliding with brackets

Also, there is no PR, but we definitely need to address what would be a blocking issue for blind users:
- [ ] https://trello.com/c/SlWCsWai/86-import-dialog-does-not-respond-to-esc-or-enter-and-not-accessible-to-screen-readers

**Comment by njvdberg** [comment]
- [ ] #7194 - Reduce score orders

**Comment by riaanvn** [comment]
* [ ] string correction: badly formed -> malformed

**Comment by Jojo-Schmitz** [comment]
* [ ] #7196 - [Fix #314910](https://musescore.org/en/node/314910): Cutaway courtesy clefs in 3.6 don't show before time signatures
* [ ] #7199 - Translatable texts fixes
* [ ] #7200 - [Fix #314642](https://musescore.org/en/node/314642): [MusicXML] big 32nd tuplet exports wrong durations

**Comment by elerouxx** [comment]
* [ ]  #7196  - [Fix #315014](https://musescore.org/en/node/315014): Cutaway courtesy clefs don't show in cutaway before time/key signatures

**Comment by Jojo-Schmitz** [comment]
* [ ] #7202 - Filter unused "customised" score orders.
* [ ] #7203 - [Fix #315106](https://musescore.org/en/node/315106): Show 2 decimals for Tempo in Play Panel

**Comment by AntonioBL** [comment]
- [ ] https://github.com/musescore/MuseScore/pull/7208 - [Fix #305215](https://musescore.org/en/node/305215) Fix import of some incomplete tuplets in MusicXML files. It also should help in XML files with complex tuplets.

**Comment by Howard-C** [comment]
Can be closed now. Or do you want to continue using this for 3.6.1?

**Comment by Jojo-Schmitz** [comment]
We'd need a new one for 3.6.1
