### ISSUE TITLE
MuseScore 3.6.1. PRs to be merged and issues to be fixed.

### ISSUE THREAD

**Issue by Jojo-Schmitz** [musescore/MuseScore#7244]
### PRs available:

* [ ] #4853 - [Fix #286900](https://musescore.org/en/node/286900): MIDI input menu has no None option
* [ ] #6494 - [Fix #309371](https://musescore.org/en/node/309371): Ambitus for transposing instruments doesn't update when toggling concert pitch _(needs some work still)_
* [ ] #6550 - [Fix #277279](https://musescore.org/en/node/277279): Lack of Capabilities in the Custom Time Signature Creator
* [ ] #6693 - [Fix #311792](https://musescore.org/en/node/311792): Override alter tag with note tuning value if present
* [ ] #6917 - Paren time sig _(needs #6550 first)_
* [ ] #7003 - [Fix #310158](https://musescore.org/en/node/310158): Don't null terminate MIDI sequence track name messages
* [ ] #7148 - [Fix #314665](https://musescore.org/en/node/314665): Don't force "long" slurs above the staff _(questionable whether we'd want this in 3.6.1)_
* [x] #7211 - [Fix #298438](https://musescore.org/en/node/298438): Correctly import notes without beams from MusicXML.
* [x] #7213 - [Fix #299976](https://musescore.org/en/node/299976): Import MusicXML beam endings
* [x] #7219 - ~Update Installer imagery for Mac and Windows~
* [x] #7227 - Create system lines also on already existing excerpts.
* [x] #7228 - Retranslate Edit Style dialog on language switch
* [x] #7241 - [Fix #315529](https://musescore.org/en/node/315529): MuseScore 3.6 crashes on open of a file with start repeat in continuous view
* [x] #7246 - Fix Windows MSI sign _(retrofitted into 3.6?)_
* [x] #7247 - Added windows portable app sign _(retrofitted into 3.6?)_
* [x] #7249 - Fix MSVC compiler warnings _(includes #7241)_
* [x] #7250 - Don't disable Qt 5.15 for 3.x
* [ ] #7256 - Export hidden tempo text to MusicXML
* [ ] #7261 - [Fix #315677](https://musescore.org/en/node/315677): Allow beaming across crotchet rests.
* [x] #7267 - Fix bogus message of the sanity check
* [x] #7269 - [Fix #315781](https://musescore.org/en/node/315781): Measure Number Offset Value Changes Everytime Opening the File
* [x] #7275 - Fix init of colors
* [x] #7278 - [Fix #284796](https://musescore.org/en/node/284796): Incomplete voice in local time signature leads to corruption upon import
* [x] #7279 - [Fix #315726](https://musescore.org/en/node/315726): Applying key change to a selection causes crash if transposing instrument is involved.
* [ ] #7292 - [Fix #315963](https://musescore.org/en/node/315963): Add Flügelhorns to instruments/orders.xml
* [x] #7293 - [Fix #315671](https://musescore.org/en/node/315671): Remove Corner Radius from Default Rehearsal Mark Style,  [fix #315503](https://musescore.org/en/node/315503): MuseScore 3.6 doesn't use self-defined Default Style for new score and [fix #315530](https://musescore.org/en/node/315530): "Keep old style" still updates style in parts (https://trello.com/c/llFAEqi1, https://trello.com/c/OxplS29w)
* [x] #7295 - [Fix #125251](https://musescore.org/en/node/125251), [fix #125191](https://musescore.org/en/node/125191), [fix #310421](https://musescore.org/en/node/310421), [fix #312877](https://musescore.org/en/node/312877): Add missing glyphs in Gootville
* [x] #7301 - [Fix #316071](https://musescore.org/en/node/316071): Display sym smufl name in symbols palette, use available translations there too _(included in #7308)_
* [x] #7304 - [Fix #315638](https://musescore.org/en/node/315638): Wrong key signature on reset styles with concert pitch
* [x] #7305 - [Fix #315841](https://musescore.org/en/node/315841): Indent can cause measures to not fit on system
* [x] #7306 - [Fix #315861](https://musescore.org/en/node/315861): Don't show clef changes on hidden staves
* [ ] #7309 - Fix tempo rounding issue in MusicXML export 
* [ ] #7310 - Store tempo more precisely in mscx/mscz files
* [x] #7314 - [Fix #309333](https://musescore.org/en/node/309333): Crash hiding palettes 
* [ ] #7315 - [Fix #316096](https://musescore.org/en/node/316096), [fix #305093](https://musescore.org/en/node/305093): Custom gliss text reverts to default "gliss"
* [x] #7328 - [Fix #315636](https://musescore.org/en/node/315636): No space between barline and note with invisible key or time signature
* [ ] #7333 - [Fix #316125](https://musescore.org/en/node/316125): Dock widgets are now focused on visibilty toggle
* [ ] #7337 - [Fix #316373](https://musescore.org/en/node/316373): Show part name in timeline rather than instrument name
* [x] #7344 - [Fix #316137](https://musescore.org/en/node/316137): Slurs on the TAB Staff move upward when inserting multiple measures
* [ ] #7345 - [Fix #275837](https://musescore.org/en/node/275837): MuseScore crashes during start-up while displaying "Start center"

### 3.5+ Regressions with no PR yet:
(Some copied across from #6505 and #6887)

* [x] ~[Fix #308925](https://musescore.org/en/node/308925): User velocity does nothing~
* [ ] [Fix #308975](https://musescore.org/en/node/308975): Display and editing of lines is wrong @RomanPudashkin 
* [ ] [Fix #311788](https://musescore.org/en/node/311788): There is a gap between the end of a staff (system) and the last barline (before a break), in case of a clef change to the next bar in a hidden instrument and show courtesy clef is on.

### Other urgent issues or earlier regressions with no PR yet:

* [x] ~[Fix #310942](https://musescore.org/en/node/310942): Freezes when clicking "Copyright and download settings" in Save Online dialog _(probably a musescore.com issue, still actual?)_~
* [x] ~[Fix #311727](https://musescore.org/en/node/311727): Can't save a score online, brings up empty dialog _(connected to the above issue, possibly no longer actual)_~
* [ ] [Fix #313298](https://musescore.org/en/node/313298): MuseScore in Microsoft Store is outdated _(and till 3.3.4!)_
* [ ] [Fix #313840](https://musescore.org/en/node/313840): Issue with saving score online when using "Upload score audio" (and a custom soundfont) _(still actual?)_

### Other long-time and frequent issues (where the real cause still is very unclear):

* [ ] Very many issues and forum posts of 'no sound', where sometimes [How to restore sound if playback stops working](https://musescore.org/en/node/96811) helps, but quite often not
* [ ] [Fix #271185](https://musescore.org/en/node/271185): Scores corrupted beyond repair, containing nothing but zeros

**Comment by Jojo-Schmitz** [comment]
* [ ] #7241 - [Fix #315529](https://musescore.org/en/node/315529): MuseScore 3.6 crashes on open of a file with start repeat in continuous view

**Comment by Howard-C** [comment]
- [ ] #7245 - Adjust measure stretch for "Dawn"

**Comment by Jojo-Schmitz** [comment]
* [ ] #7211 - [Fix #298438](https://musescore.org/en/node/298438): Correctly import notes without beams from MusicXML.
* [ ] #7213 - [Fix #299976](https://musescore.org/en/node/299976): Import MusicXML beam endings
* [ ] #7219 - Update Installer imagery for Mac and Windows

**Comment by Jojo-Schmitz** [comment]
* [ ] #7227 - Create system lines also on already existing excerpts.
* [ ] #7228 - Retranslate Edit Style dialog on language switch

**Comment by njvdberg** [comment]
- [ ] #7254 - Fix #315553 - MuseScore 3.6 Symphony Orchestra Template Violin Errors

**Comment by MarcSabatella** [comment]
#7195 (to fix https://musescore.org/en/node/312029 - fingering too small) was merged for 3.6, so that 3.5 regression is fixed already and should be removed from the list.

I'm 90% certain https://musescore.org/en/node/315554 (soundfont error) is just a user error.

Is https://musescore.org/en/node/310942 (freeze on copyright settings in save online) still an issue for people?  Hasn't happened to me in a while.

I'm still very unclear on the page margin issue that was on the list for 3.6 for the longest time and was marked resolved at one point but still seems broken to me (15.06 mm).

**Comment by MarcSabatella** [comment]
Here is a link to the Trello card for the margin issue:

- [ ] https://trello.com/c/tqV56xS9/72-fix-errant-margin-value

And here is another unsolved issue that seems to have fallen through the cracks:

- [ ] https://trello.com/c/C12fAuDS/100-space-cannot-be-entered-between-note-and-dot-in-tempo-marking
- [ ]

**Comment by cbjeukendrup** [comment]
- [ ] #7259 Set window not modified when last score is closed

**Comment by njvdberg** [comment]
- [ ] #7262 - Fix #315599 - MuseScore 3.6 crashes when rearranging instrument positions and changing Ordering

**Comment by Howard-C** [comment]
- [ ] #7265 - Link to Bilibili video if using Chinese

**Comment by Jojo-Schmitz** [comment]
* [ ] #7267 - Fix bogus message of the sanity check
* [ ] #7269 - [Fix #315781](https://musescore.org/en/node/315781): Measure Number Offset Value Changes Everytime Opening the File

**Comment by Jojo-Schmitz** [comment]
* [ ] #7269 - [Fix #315781](https://musescore.org/en/node/315781): Measure Number Offset Value Changes Everytime Opening the File
* [ ] #7295 - [Fix #125251](https://musescore.org/en/node/125251), [fix #125191](https://musescore.org/en/node/125191), [fix #310421](https://musescore.org/en/node/310421), [fix #312877](https://musescore.org/en/node/312877): Add missing glyphs in Gootville
* [ ] #7301 - [Fix #316071](https://musescore.org/en/node/316071): Display sym smufl name in symbols palette, use available translations there too
* [ ] #7305 - [Fix #315841](https://musescore.org/en/node/315841): Indent can cause measures to not fit on system
* [ ] #7306 - [Fix #315861](https://musescore.org/en/node/315861): Don't show clef changes on hidden staves

**Comment by Jojo-Schmitz** [comment]
7275* [ ] #7293 - [Fix #315671](https://musescore.org/en/node/315671): Remove Corner Radius from Default Rehearsal Mark Style plus some other fixes (https://trello.com/c/llFAEqi1, https://trello.com/c/OxplS29w)
* [ ] #7304 - [Fix #315638](https://musescore.org/en/node/315638): Wrong key signature on reset styles with concert pitch

**Comment by Jojo-Schmitz** [comment]
* [ ] #7256 - Export hidden tempo text to MusicXML
* [ ] #7261 - [Fix #315677](https://musescore.org/en/node/315677): Allow beaming across crotchet rests.
* [ ] #7278 - [Fix #284796](https://musescore.org/en/node/284796): Incomplete voice in local time signature leads to corruption upon import
* [ ] #7279 - [Fix #315726](https://musescore.org/en/node/315726): Applying key change to a selection causes crash if transposing instrument is involved.

**Comment by Jojo-Schmitz** [comment]
* [ ] #7292 - [Fix #315963](https://musescore.org/en/node/315963): Add Flügelhorns to instruments/orders.xml

**Comment by njvdberg** [comment]
- [ ] #7312 - Fix #316025 - Fixed spacers do not function with vertical justification enabled

**Comment by Jojo-Schmitz** [comment]
* [ ] #7309 - Fix tempo rounding issue in MusicXML export 
* [ ] #7310 - Store tempo more precisely in mscx/mscz files
* [ ] #7314 - [Fix #309333](https://musescore.org/en/node/309333): Crash hiding palettes 
* [ ] #7315 - [Fix #316096](https://musescore.org/en/node/316096), [fix #305093](https://musescore.org/en/node/305093): Custom gliss text reverts to default "gliss"
