### ISSUE TITLE
MuseScore 3.6.2. PRs to be merged and issues to be fixed.

### ISSUE THREAD

**Issue by Jojo-Schmitz** [musescore/MuseScore#7347]
### PRs available:

* [ ] #4853 - [Fix #286900](https://musescore.org/en/node/286900): MIDI input menu has no None option
* [ ] #6494 - [Fix #309371](https://musescore.org/en/node/309371): Ambitus for transposing instruments doesn't update when toggling concert pitch _(needs some work still)_
* [ ] #6550 - [Fix #277279](https://musescore.org/en/node/277279): Lack of Capabilities in the Custom Time Signature Creator
* [ ] #6693 - [Fix #311792](https://musescore.org/en/node/311792): Override alter tag with note tuning value if present
* [ ] #6917 - Paren time sig _(needs #6550 first)_
* [ ] #7003 - [Fix #310158](https://musescore.org/en/node/310158): Don't null terminate MIDI sequence track name messages
* [ ] #7148 - [Fix #314665](https://musescore.org/en/node/314665): Don't force "long" slurs above the staff _(questionable whether we'd want this in 3.6.2)_
* [ ] #7256 - Export hidden tempo text to MusicXML
* [x] #7261 - [Fix #315677](https://musescore.org/en/node/315677): Allow beaming across crotchet rests.
* [x] #7292 - [Fix #315963](https://musescore.org/en/node/315963): Add Flügelhorns to instruments/orders.xml
* [x] #7309 - Fix tempo rounding issue in MusicXML export 
* [x] #7310 - Store tempo more precisely in mscx/mscz files
* [x] #7315 - [Fix #316096](https://musescore.org/en/node/316096), [fix #305093](https://musescore.org/en/node/305093): Custom gliss text reverts to default "gliss"
* [x] #7333 - [Fix #316125](https://musescore.org/en/node/316125): Dock widgets are now focused on visibilty toggle
* [x] #7337 - [Fix #316373](https://musescore.org/en/node/316373): Show part name in timeline rather than instrument name
* [x] #7345 - [Fix #275837](https://musescore.org/en/node/275837): MuseScore crashes during start-up while displaying "Start center"
* [x] #7346 - Update Petaluma to 1.065
* [x] #7355 - [Fix #316502](https://musescore.org/en/node/316502): Fix accessibility of ScoreMigrationDialog
* [ ] #7356 - [Fix #315963](https://musescore.org/en/node/315963): Add missing baritone-horns and euphoniums to orders.xml and templates
* [x] #7357 - Fixed score-parts-pdf
* [x] #7359 - [Fix #287598](https://musescore.org/en/node/287598): Do not remove spanners from the measures outside of the rewrite range.
* [x] #7360 - Fix macOS dmg name, fix macOS dmg window height, update version number
* [x] #7361 - [Fix #311788](https://musescore.org/en/node/311788): Gap between staff and end barline with courtesy clef
* [x] #7362 - [Fix #315779](https://musescore.org/en/node/315779): Disable auto-size of vertical frame when dragging the height handle
* [x] #7364 - [Fix #316497](https://musescore.org/en/node/316497): Translations in 3.6.1 are outdated _(needed again though just before 3.6.2 gets released)_
* [ ] ~#7366 - [Fix #316507](https://musescore.org/en/node/316507): Application now supports using the system theme option in Windows~ _(postponed for master)_
* [x] #7368 - [Fix #316571](https://musescore.org/en/node/316571): Close icon missing on MIDI import panel 
* [x] #7370 - [Fix #315897](https://musescore.org/en/node/315897): Very strange and unreadable chord font when opening a jazz score
* [x] #7373 - [Fix #316441](https://musescore.org/en/node/316441): Crash when changing time signature in front of a corrupted measure
* [x] #7374 - g/c unused lastFocusWidget
* [x] #7380 - AppImage: Ensure zsync file is named correctly for stable releases
* [x] #7383 - [Fix #316559](https://musescore.org/en/node/316559): Style settings in score migrate to part after save / reload (https://trello.com/c/mtITOhl5/120-score-style-settings-applied-to-parts-on-reload)
* [x] #7384 - [Fix #316797](https://musescore.org/en/node/316797): Deleting a breath/caesura selects the wrong note.
* [ ] ~#7388 - Fix deprecation warnings with Qt 5.15.2 and some qml files~ _(benefit/risk ratio too low)_
* [x] #7395 - [Fix #316869](https://musescore.org/en/node/316869): mmrestrange numbers can collide with other elements
* [x] #7396 - [Fix #316754](https://musescore.org/en/node/316754): Empty rehearsal mark not deleted after entering a line break
* [x] #7400 - [Fix #315408](https://musescore.org/en/node/315408): Mixer panel not fully shown when opened
* [x] #7403 - [Fix #305777](https://musescore.org/en/node/305777): Make applying tremolo a toggle operation
* [x] #7405 - Solves potential crash when an extended instruments.xml is written.
* [x] #7407 - [Fix #316679](https://musescore.org/en/node/316679): Segmentation Fault when opening a file with a missing section break element
* [x] #7412 - [Fix #316555](https://musescore.org/en/node/316555): Invisible breath shouldn't impact layout.
* [ ] #7414 - Fixed version change when saving to file _(for 3.6.1, but needed here too? Or backend only?)_
* [ ] ~#7435 - [Fix #305387](https://musescore.org/en/node/305387): Add spinner for controlling glissando line thickness in inspector~ _(postponed due to last minute translatable string additions)_
* [x] #7439 - [Fix #316896](https://musescore.org/en/node/316896): Banjo fifth string fret numbers
* [x] #7441 - Don't save default settings to pre 3.6 score after 'reset to defaults'
* [x] #7442 - [Fix #315904](https://musescore.org/en/node/315904): [MusicXML import] incomplete import from ScoreScan XML file

### 3.5+ Regressions with no PR yet:
(Some copied across from #6505, #6887 and #7244)

* [ ] [Fix #308975](https://musescore.org/en/node/308975): Display and editing of lines is wrong @RomanPudashkin 
* [ ] https://trello.com/c/tqV56xS9/72-fix-errant-margin-value
* [ ] https://trello.com/c/C12fAuDS/100-space-cannot-be-entered-between-note-and-dot-in-tempo-marking

### Other urgent issues or earlier regressions with no PR yet:

* [ ] [Fix #313298](https://musescore.org/en/node/313298): MuseScore in Microsoft Store is outdated _(and till 3.3.4!)_
* [ ] [Fix #313840](https://musescore.org/en/node/313840): Issue with saving score online when using "Upload score audio" (and a custom soundfont) _(still actual?)_

### Other long-time and frequent issues (where the real cause still is very unclear):

* [ ] Very many issues and forum posts of 'no sound', where sometimes [How to restore sound if playback stops working](https://musescore.org/en/node/96811) helps, but quite often not
* [ ] [Fix #271185](https://musescore.org/en/node/271185): Scores corrupted beyond repair, containing nothing but zeros

**Comment by Jojo-Schmitz** [comment]
* [ ] #7355 - [Fix #316502](https://musescore.org/en/node/316502): Fix accessibility of ScoreMigrationDialog

**Comment by Jojo-Schmitz** [comment]
* [ ] #7357 - Fixed score-parts-pdf _(PR is for 3.6.1, but would be neeed in 3.x too)_
* [ ] #7360 - Fix macOS dmg name, fix macOS dmg window height, update version number

**Comment by Jojo-Schmitz** [comment]
* [ ] #7361 - [Fix #311788](https://musescore.org/en/node/311788): Gap between staff and end barline with courtesy clef
* [ ] #7362 - [Fix #315779](https://musescore.org/en/node/315779): Disable auto-size of vertical frame when dragging the height handle

**Comment by Jojo-Schmitz** [comment]
* [ ] #7363 - [Fix #316571](https://musescore.org/en/node/316571): Close icon missing on MIDI import panel

**Comment by Jojo-Schmitz** [comment]
* [ ] #7366 - [Fix #316507](https://musescore.org/en/node/316507): Application now supports using the system theme option in Windows

**Comment by Jojo-Schmitz** [comment]
* [ ] #7368 - [Fix #316571](https://musescore.org/en/node/316571): Close icon missing on MIDI import panel

**Comment by Jojo-Schmitz** [comment]
* [ ] #7370 - [Fix #315897](https://musescore.org/en/node/315897): Very strange and unreadable chord font when opening a jazz score

**Comment by Howard-C** [comment]
- [ ] #7371 - fix #316645: broken swapping notes/chords with Shift + Left/Right

**Comment by njvdberg** [comment]
- [ ] #7377 -  Fix #316610 - Staff spacer down does not work on last system of page

**Comment by Jojo-Schmitz** [comment]
* [x] #7373 - [Fix #316441](https://musescore.org/en/node/316441): Crash when changing time signature in front of a corrupted measure
* [ ] #7374 - g/c unused lastFocusWidget
* [ ] #7380 - AppImage: Ensure zsync file is named correctly for stable releases

**Comment by Jojo-Schmitz** [comment]
* [ ] #7383 - [Fix #316559](https://musescore.org/en/node/316559): Style settings in score migrate to part after save / reload (https://trello.com/c/mtITOhl5/120-score-style-settings-applied-to-parts-on-reload)

**Comment by Jojo-Schmitz** [comment]
* [ ] #7384 - [Fix #316797](https://musescore.org/en/node/316797): Deleting a breath/caesura selects the wrong note.

**Comment by Jojo-Schmitz** [comment]
* [ ] #7395 - [Fix #316869](https://musescore.org/en/node/316869): mmrestrange numbers can collide with other elements
* [ ] #7396 - [Fix #316754](https://musescore.org/en/node/316754): Empty rehearsal mark not deleted after entering a line break

**Comment by Jojo-Schmitz** [comment]
* [ ] #7400 - [Fix #315408](https://musescore.org/en/node/315408): Mixer panel not fully shown when opened

**Comment by Jojo-Schmitz** [comment]
* [ ] #7407 - [Fix #316679](https://musescore.org/en/node/316679): Segmentation Fault when opening a file with a missing section break element

**Comment by Jojo-Schmitz** [comment]
* [ ] #7412 - [Fix #316555](https://musescore.org/en/node/316555): Invisible breath shouldn't impact layout.

**Comment by Jojo-Schmitz** [comment]
* [ ] #7441 - Don't save default settings to pre 3.6 score after 'reset to defaults'
* [ ] #7442 - [Fix #315904](https://musescore.org/en/node/315904): [MusicXML import] incomplete import from ScoreScan XML file

**Comment by Jojo-Schmitz** [comment]
* [ ] #7435 - [Fix #305387](https://musescore.org/en/node/305387): Add spinner for controlling glissando line thickness in inspector
* [ ] #7439 - [Fix #316896](https://musescore.org/en/node/316896): Banjo fifth string fret numbers
