### ISSUE TITLE
[MU3 Issue] MuseScore 3.6.3 or 3.7.0, PRs to be merged and issues to be fixed.

### ISSUE THREAD

**Issue by Jojo-Schmitz** [musescore/MuseScore#7449]
### PRs available (complete list of PRs against the 3.x branch):

* [ ] #4853 - [Fix #286900](https://musescore.org/en/node/286900): MIDI input menu has no None option
* [ ] #5902 - [Fix #296528](https://musescore.org/en/node/296528): Footers now appear inside page margins
* [x] ~#6021 - [Fix #303422](https://musescore.org/en/node/303422): Lyrics color is preserved when importing mxml + small bugfix and cleanup for isEven~ _(replaced by #8034)_
* [x] ~#6080 - Adding ability to divide Fraction by integer.~ _(not needed anymore, in since 3.5.0, via another PR)
* [ ] #6095 - [Fix #305502](https://musescore.org/en/node/305502): Osc plugin controller
* [ ] #6312 - Improve horizontal spacing & vertical alignment
* [x] ~#6344 - Externally Load Fonts + Reload Without Rebuild~ _(never left draft state, got closed then)_
* [ ] #6494 - [Fix #309371](https://musescore.org/en/node/309371): Ambitus for transposing instruments doesn't update when toggling concert pitch _(still needs some work)_
* [ ] ~#6550 - [Fix #277279](https://musescore.org/en/node/277279): Lack of Capabilities in the Custom Time Signature Creator~ _(prerequisite for #6917, no 3.6.3 planned)_
* [ ] #6693 - [Fix #311792](https://musescore.org/en/node/311792): Override alter tag with note tuning value if present
* [ ] ~#6917 - Paren time sig~ _(needs #6550 first, no 3.6.3 planned)_
* [ ] #7003 - [Fix #310158](https://musescore.org/en/node/310158): Don't null terminate MIDI sequence track name messages
* [x] ~#7082 - Add transpose function to pluginAPI::score~ _(never left draft state, got closed by author)_
* [x] #7148 - [Fix #314665](https://musescore.org/en/node/314665): Don't force "long" slurs above the staff
* [x] #7179 - [Fix #314899](https://musescore.org/en/node/314899): Identical expression
* [x] #7256 - Export hidden tempo text to MusicXML
* [x] #7356 - [Fix #315963](https://musescore.org/en/node/315963): Add missing baritone-horns and euphoniums to orders.xml and templates
* [ ] ~#7388 - Fix deprecation warnings with Qt 5.15.2 and some qml files~ _(might be usefull to maintainers of the builds for Linux distributions, PR got archived)_
* [x] ~#7414 - Fixed version change when saving to file~ _(not needed any more, as the MuseScore 2 backend will get kept)_
* [x] #7435 - [Fix #305387](https://musescore.org/en/node/305387): Add spinner for controlling glissando line thickness in inspector _(needs #7704 too)_
* [ ] #7443 - [Fix #317084](https://musescore.org/en/node/317084): SVG honors z-order of staff-lines and includes Staff Type Changes
* [ ] ~#7453 - [Fix #317163](https://musescore.org/en/node/317163): Properties lost on save/reload~ _(already in master and no 3.6.3 planned)_
* [ ] ~#7455 - [Fix #316504](https://musescore.org/en/node/316504): [MusicXML import] [3.6.0 regression] fretboard incorrectly imported~ _(already in master and no 3.6.3 planned)
* [x] #7458 - [Fix #275483](https://musescore.org/en/node/275483): Give [playback cursor] a distinct color preference
* [ ] ~#7463 - Updating patch release and Copyright year as used by the installer~ _(no 3.6.3 planned)_
* [ ] #7464  - [Fix #317319](https://musescore.org/en/node/317319): C-Major/a-minor and atonal key signatures cause other elements, like dynamics, to move up
* [x] #7480  - [Fix #317368](https://musescore.org/en/node/317368): Fix Score.staves property
* [x] #7481  - [Fix #314060](https://musescore.org/en/node/314060): Onscreen Keyboard to show actual note events rather than only score selection during playback
* [ ] #7500  - [Fix #293370](https://musescore.org/en/node/293370): Allow the user to customize background when exporting as PDF/PNG/SVG _(needs #7704 too)_
* [x] #7514 - [Fix #317272](https://musescore.org/en/node/317272): Page settings dialog shows wrong values in pre-3.6 parts 
* [x] #7516 - [Fix #317424](https://musescore.org/en/node/317424): Missing tie in part after paste
* [x] #7517 - [Fix #317425](https://musescore.org/en/node/317425): Corruption/crash after repeating a 256th note or smaller. 
* [x] #7518 - [Fix #317426](https://musescore.org/en/node/317426): Rests grouped incorrectly after adding 256th note or smaller 
* [x] #7519 - [Fix #317188](https://musescore.org/en/node/317188): Allow [Q] and [W] to work on a range selection
* [ ] ~#7520 - [Fix #317438](https://musescore.org/en/node/317438): Wrong order of sagittal accidentals~ _(already in master and no 3.6.3 planned)_
* [ ] #7523 - [Fix #207346](https://musescore.org/en/node/207346): Restrict the first exported MIDI track to timing events.
* [x] #7524 - [Fix #317511](https://musescore.org/en/node/317511): Fix a crash on Undo after adding measures with timeline, [fix #320133](https://musescore.org/en/node/320133): Application Crashes When Splitting Measure, [fix #321021](https://musescore.org/en/node/321021): SegFault when undo after deleting initial 4/4 time signature if had set first measure Actual Duration to 2/4 and had chord symbols with timeline open and [fix #321023](https://musescore.org/en/node/321023): SegFault upon delete measures: tick2measure not found when timeline is open
* [x] #7529 - Reimplement spacers in vertical staves adjustment to make sure all spacers are taken into account. Also partially fixes [#317588](https://musescore.org/en/node/317588): Bad (negative) default height for fixed spacer if added to last staff of score
* [x] #7533 - [Fix #315198](https://musescore.org/en/node/315198), [fix #312737](https://musescore.org/en/node/312737), [fix #314950](https://musescore.org/en/node/314950): Fix inability to download extensions
* [x] #7544 - [Fix #317264](https://musescore.org/en/node/317264): Instruments window staves column doesn't show changed part names
* [x] #7545 - [Fix #317631](https://musescore.org/en/node/317631): Deleting all text in edit mode breaks Undo
* [x] #7546 - [Fix #317665](https://musescore.org/en/node/317665): fix REMEMBERLASTCONNECTIONS & TIMEBASEMASTER preferences not affecting jackParametersChanged
* [x] #7566 - [Fix #317703](https://musescore.org/en/node/317703): Disabling "Enable Auto-Size" for Title text in template not respected
* [x] #7569 - [Fix #317747](https://musescore.org/en/node/317747): Measure number appears after edit in first measure after section break with intervening frame
* [x] #7587 - Fixed wrong bitwise operator: & instead of |
* [x] #7590 - [Fix #313977](https://musescore.org/en/node/313977): Avoid adding a palette element twice on double-click
* [x] #7594 - Ignore SF_VERSION (from master) in 3.x
* [x] #7602 - [Fix #318035](https://musescore.org/en/node/318035): Prevent (potential) crash on MusicXML import
* [x] #7604 - Update fonts/README.md
* [x] #7606 - [Fix #318034](https://musescore.org/en/node/318034): Make Harmonium SND capable.
* [x] #7611 - [Fix #299600](https://musescore.org/en/node/299600#comment-1065170): Disable debug output for QML palette
* [x] #7612 - Fix missing translations
* [x] #7616 - [Fix #317227](https://musescore.org/en/node/317227), [fix #317185](https://musescore.org/en/node/317185): Disable centering score when opening score or switching LayoutMode
* [x] #7618 - [Fix #318251](https://musescore.org/en/node/318251): Compacting Section Break Inspector _(needs #7704 too)_
* [x] #7620 - Add "countin" tool to the toolbar in Advanced workspace
* [x] #7622 - "Add Frame Text" shortcut doesn't work
* [x] #7623 - [Fix #318327](https://musescore.org/en/node/318327): Turn on autoupdate for macOS on CI
* [x] #7628 - Fix detection of even/odd lyrics _(but see also #6021)_
* [x] #7699 - [Fix #318370](https://musescore.org/en/node/318370), [fix #318388](https://musescore.org/en/node/318388): Image paste crashes
* [x] #7703 - [Fix #316176](https://musescore.org/en/node/316176): Activating the Multimeasure rests prevents the "SmoothPan" function from working.
* [ ] #7704 - Push updated strings to Transifex, leaving old strings in place _(needed by #7435, #7500, #7618, #7872)_
* [ ] #7705 - [Fix #318534](https://musescore.org/en/node/318534): Add missing muted channels in Symphony orchestra template's Horns and Trombones
* [x] #7708 - [Fix #318546](https://musescore.org/en/node/318546): Musescore > Preferences > I/O > MIDI Output Latency field won't keep changes from 0ms
* [x] #7711 - Fix typo in a the name of a style setting
* [x] #7719 - [Fix #318646](https://musescore.org/en/node/318646): Crash when changing key signature on staff with Instruments change and transposing instruments
* [ ] #7728 - [Fix #89216](https://musescore.org/en/node/89216): Multiple possible causes of crashes or audible artefacts
* [x] #7738 - [Fix #318837](https://musescore.org/en/node/318837): Add Turkish folk music accidentals _(needs #7704 too)_
* [ ] #7739 - [Fix #297613](https://musescore.org/en/node/297613): (Linux) File save can't determine file type without extension
* [x] #7756 - [Fix #316025](https://musescore.org/en/node/316025): Solve issue of fixed spacer between last staff and bottom of page.
* [x] #7760 - [Fix #318326](https://musescore.org/en/node/318326): System Text Line missing in existing parts when added via drag&drop to non-top staff
* [x] #7776 - [Fix #317951](https://musescore.org/en/node/317951): Horizontal Frame on system by itself at end of page causes previous system to disappear
* [x] #7778 - Solve a crash when score contains a vbox which is not on top of a page. _(fixes a regression from #7529)_
* [x] #7784 - [Fix #317849](https://musescore.org/en/node/317849): MuseJazz Curly-Brace switches to another font when beyond 2 staves
* [x] #7799 - [Fix #319210](https://musescore.org/en/node/319210): MusicXML import corrupted when xml is stripped from whitespace
* [x] #7804 - [Fix #319242](https://musescore.org/en/node/319242), [fix #319020](https://musescore.org/en/node/319020): Volta/Ottava/Pedal lines disappear when switching language
* [x] #7853 - Vertical staves adjustment and single line staves
* [x] #7868 - [Fix #319476](https://musescore.org/en/node/319476): Allow plugins to add symbols to rests
* [ ] #7870 - [Fix #298147](https://musescore.org/en/node/298147), [fix #269926](https://musescore.org/en/node/269926), [fix #303450](https://musescore.org/en/node/303450): MusicXML: Handle measure number offsets, Fermatas on notes with grace notes, Text in voice 2 not placed correctly, slur and grace note (acciaccatura) fails _(still in draft)_
* [x] #7871 - [Fix #307704](https://musescore.org/en/node/307704), [fix #302104](https://musescore.org/en/node/302104), [fix #301768](https://musescore.org/en/node/301768), [fix #301016](https://musescore.org/en/node/301016) and [fix #318772](https://musescore.org/en/node/318772): Capo settings applied via staff text do not affect chord symbols, unexpected tieing behaviour, copying a partial measure leaves rest(s) missing in voices 2-4 and do not save unused images in the MSCZ archive.
* [x] #7872 - Update SMuFL to 1.4, Bravura to 1.392 and BravuraText to 1.393 _(needs #7704 too)_
* [x] #7877 - [Fix #319448](https://musescore.org/en/node/319448): Glissando tab layout and style minTieLength 
* [x] #7887 - [Fix #292716](https://musescore.org/en/node/292716), [#319525](https://musescore.org/en/node/319525): Shortcut 5 doesn't work on AZERTY keyboards
* [ ] ~#7891 - [Fix #319584](https://musescore.org/en/node/319584): Many percussions elements/sounds are not getting translated in status bar and Edit Drumset dialog~ _(needs #7704 too. Already in master and no 3.6.3 planned)_
* [ ] #7902 - On Mac don't 'install' Leland and don't 'build in' (musical) text fonts _(may solve [#316152](https://musescore.org/en/node/316152))_
* [ ] ~#7935  - [Fix #319776](https://musescore.org/en/node/319776): [MusicXML export] Invalid MusicXML will be generated if exported sheet contains tied cue notes~ _(already in master and no 3.6.3 planned, PR got archived)_
* [x] ~#7941 - Line width fix (in Page settings dialog's preview pane)~ _(for the 3.6.2 branch, as such should `git cherry-pick` cleanly into the 3.x branch. However, meanwile it got closed as not being needed)_
* [ ] ~#7947 - [Fix #319079](https://musescore.org/en/node/319079): Shift-selecting lyrics doesn't work with last word~ _(already in master and no 3.6.3 planned, PR got archived)_
* [ ] ~#7952 - [Fix #318860](https://musescore.org/en/node/318860): Rest offset with slash notation in voices > 1~ _(already in master and no 3.6.3 planned)_
* [ ] #7979 - Fix #7971: Help > MusicXML Links to contributor licenses rather than end-user licenses _(needs #7704 too)_
* [ ] ~#7987 - Fix #7970: Help > Help > About... Replace link to donate page, change its text, say GPL version~ _(needs #7704 too, already in master and no 3.6.3 planned)_)_
* [ ] ~#8000 - [Fix #318631](https://musescore.org/en/node/318631): Tablature fingering order not always correct~ _(already in master and no 3.6.3 planned)_
* [ ] ~#8008 - [Fix #320326](https://musescore.org/en/node/320326): Hide piano tool's ToolTips along with the preference setting for "ui/piano/showPitchHelp"~ _(already in master and no 3.6.3 planned, PR got archived)_
* [x] #8009 - Clean up instruments.xml _(needs #7704 too)_
* [ ] #8011 - [Fix #320517](https://musescore.org/en/node/320517): Voice 2 note stems face wrong way when noteheads made invisible
* [x] #8021 - [Fix #320620](https://musescore.org/en/node/320620): Crash when filling with slashes
* [ ] ~#8034 - [Fix #303422](https://musescore.org/en/node/303422): Importing colored lyrics from MusicXML~ _(already in master and no 3.6.3 planned)
* [ ] ~#8036 - [Fix #320573](https://musescore.org/en/node/320573): [MusicXML import] fretboard frets property not saved in MuseScore format~ _(already in master and no 3.6.3 planned)
* [ ] ~#8059 - [Fix #270988](https://musescore.org/en/node/270988): [MusicXML] first-fret tag not supported for fretboard diagrams~ _(already in master and no 3.6.3 planned)
* [ ] ~#8071 - [Fix #320973](https://musescore.org/en/node/320973): Support .cap and .capx import of (Griffschrift's) X-noteheads~ _(already in master and no 3.6.3 planned)
* [x] #8073 - Retranslate zoomBox' texts on language change
* [ ] #8074 - [Fix #320949](https://musescore.org/en/node/320949): Glissando playback (portamento) issue
* [ ] #8083 - [Fix #319778](https://musescore.org/en/node/319778): Stem protrusion in Gonville and [fix #319636](https://musescore.org/en/node/319636): Stem length too high when using Slashes (Gonville only)
* [ ] ~#8102 - [Fix #321174](https://musescore.org/en/node/321174): Organ sound for "SATB Closed Score + Organ" template is pan flute~ _(already in master and no 3.6.3 planned)
* [ ] #8111 - [Fix #321227](https://musescore.org/en/node/321227): Problems with removing empty trailing bars
* [ ] ~#8187 - [Fix #321376](https://musescore.org/en/node/321376): Musescore cannot open MusicXML file it created if filename contains an ampersand~ _(already in master and no 3.6.3 planned)
* [x] #8199 - [Fix #321730](https://musescore.org/en/node/321730): Crash on corrupt MXL import
* [ ] #8282 - [Fix #321751](https://musescore.org/en/node/321751), [fix #321753](https://musescore.org/en/node/321753): [MusicXML import] use note type instead of note duration to determine note length  and enable import of MusicXML note duration to set duration as shown in the piano roll editor _(but see also #8429)_
* [ ] #8488
* [ ] #8515
* [ ] #8578 - [Fix #316152](https://musescore.org/en/node/316152): Some characters do not print from Leland on certain printer drivers
* [ ] #8721 - [Fix #304642](https://musescore.org/en/node/304642): Crash on inspector parameter change when tie and slur selected
* [x] ~#8816~ _(but see also #8825, the better fix)_
* [ ] #9019
* [ ] #9081
* [ ] #9236
* [ ] #9238

### PRs for master that would apply to 3.x and seem worth getting backported:

* [ ] #5003 _(needs to get backported/rebased and fixed, got closed/archived meanwhile, but is still valid IMHO)_
* [ ] #5414
* [ ] #7744 (partially) <!--done-->
* [ ] #7957 <!--partly done-->
* [x] ~#7995~ _(got closed meanwhile)_, see #8099
* [ ] #7997
* [ ] #8099
* [ ] #8137  _(got closed meanwhile, but still seems worthwhile IMHO)_ <!--done-->
* [x] ~#8140~ _(got closed meanwhile)_
* [ ] #8141 <!--done-->
* [ ] #8142 <!--done-->
* [ ] #8146 <!--done-->
* [ ] #8170 <!--done-->
* [x] ~#8180~ _(got closed meanwhile)_
* [ ] #8244 <!--done-->
* [ ] #8254 <!--done-->
* [ ] #8273
* [ ] #8279
* [ ] #8289 <!--done-->
* [ ] #8424 <!--done-->
* [ ] #8425 _(needs #8273 first)_
* [ ] #8429 _(but see also #8282)_ <!--done-->
* [ ] #8431
* [ ] #8493 <!--done-->
* [ ] #8510 <!--done-->
* [x] ~#8514~ _(got closed meanwhile, collides with #8190)_
* [ ] #8600 <!--done-->
* [ ] #8762  (partially) <!--done-->
* [ ] #8765 (partially, the parts not related to Unity builds) <!--done-->
* [ ] #8772 <!--done-->
* [ ] #8775 (partially, the part fixing [Fix #284064](https://musescore.org/en/node/284064): "Respell pitches" should only work on the selection, if there is any) <!--done-->
* [ ] #8793 <!--done-->
* [ ] #8808 <!--done-->
* [ ] #8818 _(Fixing a regression from #8510)_ <!--done-->
* [ ] #8825 _better/different way to fix the issue from #8816)_ <!--done-->
* [ ] #8833 <!--done-->
* [ ] #8835 <!--done--> _(needs #7704)_
* [ ] #8877 <!--done--> _(needs #7704, but see also #7870)_
* [ ] #8894 <!--done--> _(needs #7704)_
* [ ] #8903 <!--done-->
* [ ] #8919 <!--done-->
* [ ] #8953 <!--done--><!-- #8956 maybe?-->
* [ ] #8958: https://trello.com/c/86Ks7zZX/58-stemdownnw-stemupse-not-honoured-for-x-notehead <!--done--><!--* #8867 _(huge, worth the effort?)_--><!--* [ ] #8976 huge, worth the effort?-->
* [ ] #8978 <!--done-->
* [ ] #8979 <!--done-->
* [ ] #8985 <!--done-->
* [ ] #9001 <!--done-->
* [ ] #9068 <!--very party done-->
* [ ] #9077 <!--done-->
* [ ] #9086 <!--done-->
* [ ] #9092
* [ ] #9095 <!--done-->
* [ ] #9097 <!--done-->
* [ ] #9104 <!--done-->
* [ ] #9126 <!--done-->
* [ ] #9137 <!--done-->
* [ ] #9138 <!--done-->
* [ ] #9140 <!--done-->
* [ ] #9193 <!--done-->
* [ ] #9219 <!--done-->
* [ ] #9237 _( quite big)_


### PRs available (complete list of PRs against the 3.6.2_backend branch not yet merged into 3.x, which should cherry-pick cleanly): <!--all done once merged into 3.6.2_backend, exceptions listed below in a comment-->

* [ ] #8108 
* [ ] #8116
* [ ] #8133
* [ ] #8175
* [ ] #8176
* [ ] #8181
* [ ] #8190
* [ ] #8237
* [ ] #8275
* [ ] #8283
* [ ] #8284
* [ ] #8285
* [ ] #8296
* [ ] #8298
* [ ] #8311
* [ ] #8325
* [ ] #8326
* [ ] #8347
* [ ] #8358
* [ ] #8412
* [ ] #8413
* [ ] #8430 (but see https://github.com/musescore/MuseScore/pull/8430#pullrequestreview-698705061)
* [ ] #8433
* [x] ~#8447~ (see #8763 instead)
* [ ] #8461
* [ ] #8478
* [ ] #8480
* [ ] #8481
* [ ] #8492
* [ ] #8506
* [ ] #8509
* [ ] #8527
* [ ] #8530
* [ ] #8554 <!--merged as part of the commit that caused these warnings-->
* [ ] #8556
* [ ] #8581 
* [ ] #8583
* [ ] #8613
* [x] ~#8619~ (see #8636 instead)
* [ ] #8622
* [ ] #8623
* [ ] #8636
* [ ] #8637
* [ ] #8649
* [ ] #8651
* [ ] #8678
* [x] ~#8688~ (see #8766 instead)
* [x] ~#8742~ (see #8766 instead)
* [ ] #8763 <!--causing issues, so far of the 15 commits merged only the 1st and 2nd, skipped the 3rd which is of dubious value and fails its own mtest too(?!?), the 4th, which depends on it and the 5th, depends on it too (and also on the skipped middle commit from #8766), merged the 6th, skipped 7th and 8th which both need the 3rd etc., merged the 9th, skippen the 10th due to merge issues, seems to need one of the skipped commits, merged the 11th and 12th, skipping 13th,14th and 15th, these need previously skippend one-->
* [ ] #8766 <!--Todo: ENG-85, the middle commit-->
* [ ] #8866

### 3.5+ Regressions with no PR yet:
(Some copied across from #6505, #6887, #7244, #7347)

* [ ] <!--#6353 - -->[Fix #287131](https://musescore.org/en/node/287131): MusicXML import ignores string/fret  @lvinken ?
* [ ] <!--#6353 - -->[Fix #308975](https://musescore.org/en/node/308975): Display and editing of lines is wrong @RomanPudashkin 
* [ ] https://trello.com/c/tqV56xS9/72-fix-errant-margin-value
* [ ] https://trello.com/c/C12fAuDS/100-space-cannot-be-entered-between-note-and-dot-in-tempo-marking
* [ ] <!--#6353 - -->[Fix #317230](https://musescore.org/en/node/317230): MusicXML: credit-words text can overlay staves  @lvinken ?
* [ ] <!--#6353 - -->[Fix #317565](https://musescore.org/en/node/317565): "I" shortcut (Instruments dialog) no longer works as expected _(may be seen as by design, needed for accessibility)_
* [ ] <!--#6353 - -->[Fix #319822](https://musescore.org/en/node/319822): Plugin documentation has not been updated for 3.6
* [ ] <!--#6353 - -->[Fix #320641](https://musescore.org/en/node/320641): Right-aligned text in Edwin isn't aligned, depending on kernings  @oktophonie ?
* [ ] <!--#6353 - -->[Fix #318773](https://musescore.org/en/node/318773): Glissando on final tied note causes it to repeat, rather than sustain
* [ ] <!--#6353 - -->[Fix #321094](https://musescore.org/en/node/321094): Undoing a clef change when the other linked staff does not display one leads to a crash
* [x] <!--#6353 - -->[Fix #323561](https://musescore.org/en/node/323561): Chord notation won't print correctly when using Edwin on a Mac and an HP printer  @oktophonie ?
* [ ] <!--#6353 - -->[Fix #324706](https://musescore.org/en/node/324706): Crash when opening a certain score from 2.0.x

### 3.x regression (post 3.6.2 release)

* [x] <!--#6353 - -->#8161  @oktophonie ?

### Other urgent issues or earlier regressions with no PR yet:

* [ ] <!--#6353 - -->[Fix #306066](https://musescore.org/en/node/306066): Updated build for ARM _(and since 2.1!)_
* [ ] <!--#6353 - -->[Fix #313298](https://musescore.org/en/node/313298): MuseScore in Microsoft Store is outdated _(and since 3.3.4!)_
* [ ] <!--#6353 - -->[Fix #313840](https://musescore.org/en/node/313840): Issue with saving score online when using "Upload score audio" (and a custom soundfont) _(still actual?)_
* [ ] <!--#6353 - -->[Fix #318866](https://musescore.org/en/node/318866): MP3 export fails for instruments not set for Single Note Dynamics, but set for using an "expr." sound _(intruduced some time after 3.2.3)_

### Other long-time and frequent issues (where the real cause still is very unclear):

* [ ] Very many issues and forum posts of 'no sound', where sometimes [How to restore sound if playback stops working](https://musescore.org/en/node/96811) helps, but quite often not
* [ ] <!--#6353 - -->[Fix #271185](https://musescore.org/en/node/271185): Scores corrupted beyond repair, containing nothing but zeros

**Comment by Howard-C** [comment]
Isn't "improve horizontal spacing & vertical alignment" #6312?

**Comment by Jojo-Schmitz** [comment]
yes, corrected

**Comment by Howard-C** [comment]
Why has it been deleted?

**Comment by Jojo-Schmitz** [comment]
No idea, fat fingers probably

**Comment by cbjeukendrup** [comment]
- [ ] PR #7616: Fix #317227, fix #317185: Disable centering score when opening score or switching LayoutMode

**Comment by Jojo-Schmitz** [comment]
Added in the initial post already ;-)

**Comment by MarcSabatella** [comment]
I have no idea what #7941 is supposed to fix, but as far as I can tell, all it does is break something that works perfectly now (scaling of line width as you change scaling for the score).

**Comment by Jojo-Schmitz** [comment]
We'll see whether it turns into something useful. I've just listed is as a potential candidate.

**Comment by Tantacrul** [comment]
@Jojo-Schmitz - should this be closed now, since it is so old?

**Comment by Jojo-Schmitz** [comment]
I don't think so, there are enough things left that have not yet been ported, or at least not been checked for the neccessity.

**Comment by Jojo-Schmitz** [comment]
Hmm, actually I meant #6079
The thinks from thos issue here are mostly done on #9000 and there still isn't any further 3.x planned
