### ISSUE TITLE
[MU4 Task] Tooltips

### ISSUE THREAD

**Issue by vpereverzev** [musescore/MuseScore#8168]
**Task description**
- Rewrite our QmlToolTip from qwidgets to qml. Instead of using QToolTip need to use our PopupView
- Implement the view of tooltip

![image](https://user-images.githubusercontent.com/10116828/118866866-bd1f5900-b8e2-11eb-83e6-05b711d3c4fa.png)

**Comment by cbjeukendrup** [comment]
**ToDo** (in my view):
- [ ] At least on macOS, tooltips sometimes appear slightly too much to the right:
    <img width="540" alt="Schermafbeelding 2021-05-27 om 14 41 52" src="https://user-images.githubusercontent.com/48658420/119827666-b05dbf00-bef9-11eb-9bf2-98a1c4819e03.png">
- [ ] Also at least on macOS, tooltips (like any other PopupView) appear behind undocked dock widgets:
  <img width="540" alt="Schermafbeelding 2021-05-27 om 14 43 49" src="https://user-images.githubusercontent.com/48658420/119827927-f4e95a80-bef9-11eb-81fd-c27a1440c48d.png">
- [ ] When a tooltip is shown, the main window looses the focus (see the close/minimize/fullscreen buttons on macOS). I think this is annoying:

  https://user-images.githubusercontent.com/48658420/119828074-1cd8be00-befa-11eb-8150-d020e21182a0.mov

- [ ] When a tooltip is shown and you move to another button, the tooltip for that other button should be shown directly, instead of after the delay. I believe this is common behaviour in other apps too. @Tantacrul do you agree about this one?
