### ISSUE TITLE
[MU4 Task] Implement remaining functionality of Preferences dialog

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#9807]
**Task description**
The UI for the Preferences dialog is already fully built, but some options are not functional yet. Either the functionality needs to be implemented, or the controls need to be removed if they are not actual anymore for MuseScore 4.

It concerns the following options:
- [ ] #12223
- [x] ~General > OSC Remote Control~
    This feature is not present in MU4.0 anyway and the UI for it is hidden
- [x] (Program Start > Show splash screen: the value is stored to the configuration, but not used from there)
    #11330 
- [x] ~Folders: SoundFonts and Images don't work yet~
    SoundFonts works now, and Images is removed in #12096.
- [ ] Note input: some values are stored to the configuration but never read
    - [x] #10774 
    - [x] "Advance to next note on key release (MIDI)"
    - [x] "Colour notes outside of usable pitch range" (need to rename: "colour" -> "color")
    - [ ] #12224
    - [x] "Play notes when editing"
    - [x] "Play chord [...]"
    - [ ] #10921: "Play chord symbol [...]" setting not yet connected
- [x] ~(Score > View: the value is stored to the configuration, but not used from there)~ This section has been removed
- [ ] IO: 
    - [ ] #11748 (in progress, by Elnur)
    - [ ] sample rate, buffer size, etc.
- [ ] #12225
- [x] (Update: the values are stored to the configurations, but: #9163.)

**Comment by Tantacrul** [comment]
@cbjeukendrup - can you amend this as needed and add a P number as you see fit!

**Comment by cbjeukendrup** [comment]
I’m not assigning anyone specifically for now, because this will likely be tackled in several steps by multiple developers, and also community members may want to help. But it is on the radar!

**Comment by Tantacrul** [comment]
Related P0 for 'Devices'.

Whoever works on these, please do get in touch and we can discuss what to do if anything here is problematic.

**Comment by wizofaus** [comment]
Is there an intention to split this up?  Happy to help out as needed, but wouldn't take it all on in one go!

**Comment by cbjeukendrup** [comment]
@wizofaus Yes, the plan is to tackle this in steps. I'm planning to work on this during the coming week, so please let me know which part(s) you would like to work on.

**Comment by wizofaus** [comment]
None in particular,  just looking for things that can be tackled with small changes.

**Comment by Eism** [comment]
I am working on IO page

**Comment by wizofaus** [comment]
Still no movement on breaking this up at all?

**Comment by cbjeukendrup** [comment]
I've updated the description with the current situation. There are four remaining tasks:
- General > Keyboard layout
- Two settings on the note input page are not yet connected
- The IO page, but that's already being worked on
- Import > Style used for import

I will create separate issues for those tasks.

**Comment by RomanPudashkin** [comment]
Let's close this issue, since we already have issues for all the remaining tasks
